// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package twins

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/interactive"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var retrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "twin-id", Shorthand: "t", FieldPath: "TwinID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "wait-for", Shorthand: "w", FieldPath: "WaitFor", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=wait_for"`, Description: "options: ready, stopped"},
}

// initRetrieveCmd initializes the retrieve command.
func initRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "retrieve [twin-id]",
		Short:   "Retrieve a twin",
		Long:    "With `wait_for`, the answer is held until the twin reaches that state, a run of it settles, or the wait runs out — so a caller waiting for a twin to serve sends one request rather than polling.",
		Example: "  twinbay twins retrieve --twin-id 976bd5dd-5c1a-4781-9b8f-3e0e0de5753c",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runRetrieveCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "get_environment_twin",
		},
	}
	flagutil.RegisterFlags(cmd, retrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetEnvironmentTwinRequest](retrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for retrieve: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "twin-id", "string value (or pass it as the [twin-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "twin-id", Summary: "string value", Required: true, SatisfiedBy: []string{"twin-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRetrieveCmd executes the retrieve command.
func runRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.GetEnvironmentTwinRequest](cmd, retrieveCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Twins.Retrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
