// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type AdvanceEnvironmentRequest struct {
	EnvironmentID     string                               `pathParam:"style=simple,explode=false,name=environment_id"`
	EnvironmentTwinID string                               `pathParam:"style=simple,explode=false,name=environment_twin_id"`
	Body              components.AdvanceEnvironmentRequest `request:"mediaType=application/json"`
}

func (a *AdvanceEnvironmentRequest) GetEnvironmentID() string {
	if a == nil {
		return ""
	}
	return a.EnvironmentID
}

func (a *AdvanceEnvironmentRequest) GetEnvironmentTwinID() string {
	if a == nil {
		return ""
	}
	return a.EnvironmentTwinID
}

func (a *AdvanceEnvironmentRequest) GetBody() components.AdvanceEnvironmentRequest {
	if a == nil {
		return components.AdvanceEnvironmentRequest{}
	}
	return a.Body
}

type AdvanceEnvironmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseAdvanceEnvironment map[string]int64
}

func (a AdvanceEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdvanceEnvironmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdvanceEnvironmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AdvanceEnvironmentResponse) GetResponseAdvanceEnvironment() map[string]int64 {
	if a == nil {
		return nil
	}
	return a.ResponseAdvanceEnvironment
}
