// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type CreateEnvironmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EnvironmentResponse *components.EnvironmentResponse
}

func (c CreateEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEnvironmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEnvironmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEnvironmentResponse) GetEnvironmentResponse() *components.EnvironmentResponse {
	if c == nil {
		return nil
	}
	return c.EnvironmentResponse
}
