// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type CreateEvaluationRequest struct {
	TestRunID string `pathParam:"style=simple,explode=false,name=test_run_id"`
	// Replaying the same key and payload returns the same evaluation; reusing it with a different payload answers 409.
	IdempotencyKey optionalnullable.OptionalNullable[string] `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.CreateEvaluationRequest        `request:"mediaType=application/json"`
}

func (c *CreateEvaluationRequest) GetTestRunID() string {
	if c == nil {
		return ""
	}
	return c.TestRunID
}

func (c *CreateEvaluationRequest) GetIdempotencyKey() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateEvaluationRequest) GetBody() components.CreateEvaluationRequest {
	if c == nil {
		return components.CreateEvaluationRequest{}
	}
	return c.Body
}

type CreateEvaluationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EvaluationResponse *components.EvaluationResponse
}

func (c CreateEvaluationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEvaluationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEvaluationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEvaluationResponse) GetEvaluationResponse() *components.EvaluationResponse {
	if c == nil {
		return nil
	}
	return c.EvaluationResponse
}
