// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type CreateTestRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestRunResponse *components.TestRunResponse
}

func (c CreateTestRunResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTestRunResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTestRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTestRunResponse) GetTestRunResponse() *components.TestRunResponse {
	if c == nil {
		return nil
	}
	return c.TestRunResponse
}
