// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type CreateScenarioResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ScenarioResponse *components.ScenarioResponse
}

func (c CreateScenarioResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateScenarioResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateScenarioResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateScenarioResponse) GetScenarioResponse() *components.ScenarioResponse {
	if c == nil {
		return nil
	}
	return c.ScenarioResponse
}
