// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type CreateTestVersionRequest struct {
	TestID string                              `pathParam:"style=simple,explode=false,name=test_id"`
	Body   components.CreateTestVersionRequest `request:"mediaType=application/json"`
}

func (c *CreateTestVersionRequest) GetTestID() string {
	if c == nil {
		return ""
	}
	return c.TestID
}

func (c *CreateTestVersionRequest) GetBody() components.CreateTestVersionRequest {
	if c == nil {
		return components.CreateTestVersionRequest{}
	}
	return c.Body
}

type CreateTestVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestVersionResponse *components.TestVersionResponse
}

func (c CreateTestVersionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTestVersionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTestVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTestVersionResponse) GetTestVersionResponse() *components.TestVersionResponse {
	if c == nil {
		return nil
	}
	return c.TestVersionResponse
}
