// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
)

type DeleteEnvironmentTemplateRequest struct {
	TemplateID string `pathParam:"style=simple,explode=false,name=template_id"`
}

func (d *DeleteEnvironmentTemplateRequest) GetTemplateID() string {
	if d == nil {
		return ""
	}
	return d.TemplateID
}

type DeleteEnvironmentTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteEnvironmentTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
