// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
)

type DeleteSeedRequest struct {
	SeedID string `pathParam:"style=simple,explode=false,name=seed_id"`
}

func (d *DeleteSeedRequest) GetSeedID() string {
	if d == nil {
		return ""
	}
	return d.SeedID
}

type DeleteSeedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteSeedResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
