// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
)

type DeleteScenarioRequest struct {
	ScenarioID string `pathParam:"style=simple,explode=false,name=scenario_id"`
}

func (d *DeleteScenarioRequest) GetScenarioID() string {
	if d == nil {
		return ""
	}
	return d.ScenarioID
}

type DeleteScenarioResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteScenarioResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
