// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type DownloadExportRequest struct {
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
	ExportID      string `pathParam:"style=simple,explode=false,name=export_id"`
}

func (d *DownloadExportRequest) GetEnvironmentID() string {
	if d == nil {
		return ""
	}
	return d.EnvironmentID
}

func (d *DownloadExportRequest) GetExportID() string {
	if d == nil {
		return ""
	}
	return d.ExportID
}

type DownloadExportResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ExportDownloadResponse *components.ExportDownloadResponse
}

func (d DownloadExportResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DownloadExportResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DownloadExportResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DownloadExportResponse) GetExportDownloadResponse() *components.ExportDownloadResponse {
	if d == nil {
		return nil
	}
	return d.ExportDownloadResponse
}
