// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type WaitFor string

const (
	WaitForReady   WaitFor = "ready"
	WaitForStopped WaitFor = "stopped"
)

func (e WaitFor) ToPointer() *WaitFor {
	return &e
}
func (e *WaitFor) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ready":
		fallthrough
	case "stopped":
		*e = WaitFor(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WaitFor: %v", v)
	}
}

type GetEnvironmentTwinRequest struct {
	TwinID  string                                     `pathParam:"style=simple,explode=false,name=twin_id"`
	WaitFor optionalnullable.OptionalNullable[WaitFor] `queryParam:"style=form,explode=true,name=wait_for"`
}

func (g *GetEnvironmentTwinRequest) GetTwinID() string {
	if g == nil {
		return ""
	}
	return g.TwinID
}

func (g *GetEnvironmentTwinRequest) GetWaitFor() optionalnullable.OptionalNullable[WaitFor] {
	if g == nil {
		return nil
	}
	return g.WaitFor
}

type GetEnvironmentTwinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EnvironmentTwinResponse *components.EnvironmentTwinResponse
}

func (g GetEnvironmentTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEnvironmentTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEnvironmentTwinResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEnvironmentTwinResponse) GetEnvironmentTwinResponse() *components.EnvironmentTwinResponse {
	if g == nil {
		return nil
	}
	return g.EnvironmentTwinResponse
}
