// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type GetEnvironmentRequest struct {
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
}

func (g *GetEnvironmentRequest) GetEnvironmentID() string {
	if g == nil {
		return ""
	}
	return g.EnvironmentID
}

type GetEnvironmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EnvironmentResponse *components.EnvironmentResponse
}

func (g GetEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEnvironmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEnvironmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEnvironmentResponse) GetEnvironmentResponse() *components.EnvironmentResponse {
	if g == nil {
		return nil
	}
	return g.EnvironmentResponse
}
