// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type GetRequestLogRequest struct {
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
	RequestID     string `pathParam:"style=simple,explode=false,name=request_id"`
}

func (g *GetRequestLogRequest) GetEnvironmentID() string {
	if g == nil {
		return ""
	}
	return g.EnvironmentID
}

func (g *GetRequestLogRequest) GetRequestID() string {
	if g == nil {
		return ""
	}
	return g.RequestID
}

type GetRequestLogResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	RequestLogResponse *components.RequestLogResponse
}

func (g GetRequestLogResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRequestLogResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetRequestLogResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRequestLogResponse) GetRequestLogResponse() *components.RequestLogResponse {
	if g == nil {
		return nil
	}
	return g.RequestLogResponse
}
