// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type GetSeedRequest struct {
	SeedID string `pathParam:"style=simple,explode=false,name=seed_id"`
}

func (g *GetSeedRequest) GetSeedID() string {
	if g == nil {
		return ""
	}
	return g.SeedID
}

type GetSeedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SeedResponse *components.SeedResponse
}

func (g GetSeedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSeedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSeedResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSeedResponse) GetSeedResponse() *components.SeedResponse {
	if g == nil {
		return nil
	}
	return g.SeedResponse
}
