// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type WaitFor string

const (
	WaitForReady   WaitFor = "ready"
	WaitForStopped WaitFor = "stopped"
)

func (e WaitFor) ToPointer() *WaitFor {
	return &e
}
func (e *WaitFor) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ready":
		fallthrough
	case "stopped":
		*e = WaitFor(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WaitFor: %v", v)
	}
}

type GetSandboxTwinRequest struct {
	SandboxID     string                                     `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID string                                     `pathParam:"style=simple,explode=false,name=sandbox_twin_id"`
	WaitFor       optionalnullable.OptionalNullable[WaitFor] `queryParam:"style=form,explode=true,name=wait_for"`
}

func (g *GetSandboxTwinRequest) GetSandboxID() string {
	if g == nil {
		return ""
	}
	return g.SandboxID
}

func (g *GetSandboxTwinRequest) GetSandboxTwinID() string {
	if g == nil {
		return ""
	}
	return g.SandboxTwinID
}

func (g *GetSandboxTwinRequest) GetWaitFor() optionalnullable.OptionalNullable[WaitFor] {
	if g == nil {
		return nil
	}
	return g.WaitFor
}

type GetSandboxTwinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SandboxTwinResponse *components.SandboxTwinResponse
}

func (g GetSandboxTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSandboxTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSandboxTwinResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSandboxTwinResponse) GetSandboxTwinResponse() *components.SandboxTwinResponse {
	if g == nil {
		return nil
	}
	return g.SandboxTwinResponse
}
