// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d26d023937a0

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type GetTwinRequest struct {
	TwinSlug string `pathParam:"style=simple,explode=false,name=twin_slug"`
}

func (g *GetTwinRequest) GetTwinSlug() string {
	if g == nil {
		return ""
	}
	return g.TwinSlug
}

type GetTwinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TwinResponse *components.TwinResponse
}

func (g GetTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTwinResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTwinResponse) GetTwinResponse() *components.TwinResponse {
	if g == nil {
		return nil
	}
	return g.TwinResponse
}
