// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: baf3be24c89f

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type GetTestRunRequest struct {
	TestRunID string `pathParam:"style=simple,explode=false,name=test_run_id"`
}

func (g *GetTestRunRequest) GetTestRunID() string {
	if g == nil {
		return ""
	}
	return g.TestRunID
}

type GetTestRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestRunResponse *components.TestRunResponse
}

func (g GetTestRunResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTestRunResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTestRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTestRunResponse) GetTestRunResponse() *components.TestRunResponse {
	if g == nil {
		return nil
	}
	return g.TestRunResponse
}
