// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 08e0e3054486

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type InviteCurrentOrganizationMemberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	InvitationResponse *components.InvitationResponse
}

func (i InviteCurrentOrganizationMemberResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InviteCurrentOrganizationMemberResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InviteCurrentOrganizationMemberResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InviteCurrentOrganizationMemberResponse) GetInvitationResponse() *components.InvitationResponse {
	if i == nil {
		return nil
	}
	return i.InvitationResponse
}
