// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 735aec5d3069

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListTwinsRequest struct {
	// Sort by display name, A-Z (case-insensitive).
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	sort optionalnullable.OptionalNullable[string] `const:"name" queryParam:"style=form,explode=true,name=sort"`
	Page *int64                                    `default:"1" queryParam:"style=form,explode=true,name=page"`
	Size *int64                                    `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListTwinsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTwinsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTwinsRequest) GetSort() optionalnullable.OptionalNullable[string] {
	var tmp string = "name"
	return optionalnullable.From[string](&tmp)
}

func (l *ListTwinsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListTwinsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListTwinsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageTwinResponse *components.PageTwinResponse

	Next func() (*ListTwinsResponse, error)
}

func (l ListTwinsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTwinsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTwinsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTwinsResponse) GetPageTwinResponse() *components.PageTwinResponse {
	if l == nil {
		return nil
	}
	return l.PageTwinResponse
}
