// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c07326fa077a

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListInvoicesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	InvoicesResponse *components.InvoicesResponse
}

func (l ListInvoicesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInvoicesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInvoicesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListInvoicesResponse) GetInvoicesResponse() *components.InvoicesResponse {
	if l == nil {
		return nil
	}
	return l.InvoicesResponse
}
