// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListSeedSuggestionsRequest struct {
	// Only suggestions for this twin's slug.
	Twin optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=twin"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListSeedSuggestionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSeedSuggestionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSeedSuggestionsRequest) GetTwin() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Twin
}

func (l *ListSeedSuggestionsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSeedSuggestionsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListSeedSuggestionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageSeedSuggestionResponse *components.PageSeedSuggestionResponse
}

func (l ListSeedSuggestionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSeedSuggestionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSeedSuggestionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSeedSuggestionsResponse) GetPageSeedSuggestionResponse() *components.PageSeedSuggestionResponse {
	if l == nil {
		return nil
	}
	return l.PageSeedSuggestionResponse
}
