// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 158563a04bef

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListTestsRequest struct {
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListTestsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTestsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTestsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListTestsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListTestsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageTestResponse *components.PageTestResponse

	Next func() (*ListTestsResponse, error)
}

func (l ListTestsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTestsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTestsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTestsResponse) GetPageTestResponse() *components.PageTestResponse {
	if l == nil {
		return nil
	}
	return l.PageTestResponse
}
