// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListSeedSuggestionsRequest struct {
	// Only suggestions for this twin's slug.
	Twin optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=twin"`
}

func (l *ListSeedSuggestionsRequest) GetTwin() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Twin
}

type ListSeedSuggestionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListSeedSuggestions []components.SeedSuggestionResponse
}

func (l ListSeedSuggestionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSeedSuggestionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSeedSuggestionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSeedSuggestionsResponse) GetResponseListSeedSuggestions() []components.SeedSuggestionResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListSeedSuggestions
}
