// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListTestRunsRequest struct {
	EnvironmentID optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=environment_id"`
	TestVersionID optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=test_version_id"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListTestRunsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTestRunsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTestRunsRequest) GetEnvironmentID() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.EnvironmentID
}

func (l *ListTestRunsRequest) GetTestVersionID() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.TestVersionID
}

func (l *ListTestRunsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListTestRunsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListTestRunsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageTestRunResponse *components.PageTestRunResponse
}

func (l ListTestRunsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTestRunsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTestRunsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTestRunsResponse) GetPageTestRunResponse() *components.PageTestRunResponse {
	if l == nil {
		return nil
	}
	return l.PageTestRunResponse
}
