// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7b87c1c3d9c1

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListCurrentOrganizationMembersRequest struct {
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListCurrentOrganizationMembersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCurrentOrganizationMembersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCurrentOrganizationMembersRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListCurrentOrganizationMembersRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListCurrentOrganizationMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageOrganizationMemberResponse *components.PageOrganizationMemberResponse

	Next func() (*ListCurrentOrganizationMembersResponse, error)
}

func (l ListCurrentOrganizationMembersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCurrentOrganizationMembersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCurrentOrganizationMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCurrentOrganizationMembersResponse) GetPageOrganizationMemberResponse() *components.PageOrganizationMemberResponse {
	if l == nil {
		return nil
	}
	return l.PageOrganizationMemberResponse
}
