// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f34bebeb2ee5

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListCurrentOrganizationInvitationsRequest struct {
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListCurrentOrganizationInvitationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCurrentOrganizationInvitationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCurrentOrganizationInvitationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListCurrentOrganizationInvitationsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListCurrentOrganizationInvitationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageInvitationResponse *components.PageInvitationResponse

	Next func() (*ListCurrentOrganizationInvitationsResponse, error)
}

func (l ListCurrentOrganizationInvitationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCurrentOrganizationInvitationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCurrentOrganizationInvitationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCurrentOrganizationInvitationsResponse) GetPageInvitationResponse() *components.PageInvitationResponse {
	if l == nil {
		return nil
	}
	return l.PageInvitationResponse
}
