// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type ListAPIKeysRequest struct {
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListAPIKeysRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAPIKeysRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAPIKeysRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListAPIKeysRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListAPIKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// One page of the organization's keys
	PageAPIKeyResponse *components.PageAPIKeyResponse

	Next func() (*ListAPIKeysResponse, error)
}

func (l ListAPIKeysResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAPIKeysResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAPIKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAPIKeysResponse) GetPageAPIKeyResponse() *components.PageAPIKeyResponse {
	if l == nil {
		return nil
	}
	return l.PageAPIKeyResponse
}
