// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 45a97fdcb0f6

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type RenameCurrentOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The renamed organization and the caller's role in it
	MembershipResponse *components.MembershipResponse
}

func (r RenameCurrentOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RenameCurrentOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RenameCurrentOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RenameCurrentOrganizationResponse) GetMembershipResponse() *components.MembershipResponse {
	if r == nil {
		return nil
	}
	return r.MembershipResponse
}
