// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 71a57ac68895

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
)

type RevokeAPIKeyRequest struct {
	APIKeyID string `pathParam:"style=simple,explode=false,name=api_key_id"`
}

func (r *RevokeAPIKeyRequest) GetAPIKeyID() string {
	if r == nil {
		return ""
	}
	return r.APIKeyID
}

type RevokeAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (r *RevokeAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}
