// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type StartEnvironmentTwinRequest struct {
	TwinID string `pathParam:"style=simple,explode=false,name=twin_id"`
}

func (s *StartEnvironmentTwinRequest) GetTwinID() string {
	if s == nil {
		return ""
	}
	return s.TwinID
}

type StartEnvironmentTwinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EnvironmentTwinResponse *components.EnvironmentTwinResponse
}

func (s StartEnvironmentTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartEnvironmentTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StartEnvironmentTwinResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StartEnvironmentTwinResponse) GetEnvironmentTwinResponse() *components.EnvironmentTwinResponse {
	if s == nil {
		return nil
	}
	return s.EnvironmentTwinResponse
}
