// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type UpdateScenarioRequest struct {
	ScenarioID string                           `pathParam:"style=simple,explode=false,name=scenario_id"`
	Body       components.UpdateScenarioRequest `request:"mediaType=application/json"`
}

func (u *UpdateScenarioRequest) GetScenarioID() string {
	if u == nil {
		return ""
	}
	return u.ScenarioID
}

func (u *UpdateScenarioRequest) GetBody() components.UpdateScenarioRequest {
	if u == nil {
		return components.UpdateScenarioRequest{}
	}
	return u.Body
}

type UpdateScenarioResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ScenarioResponse *components.ScenarioResponse
}

func (u UpdateScenarioResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateScenarioResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateScenarioResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateScenarioResponse) GetScenarioResponse() *components.ScenarioResponse {
	if u == nil {
		return nil
	}
	return u.ScenarioResponse
}
