// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type UpdateEnvironmentRecordRequest struct {
	TwinID     string                                    `pathParam:"style=simple,explode=false,name=twin_id"`
	Resource   string                                    `pathParam:"style=simple,explode=false,name=resource"`
	ExternalID string                                    `pathParam:"style=simple,explode=false,name=external_id"`
	Body       components.UpdateEnvironmentRecordRequest `request:"mediaType=application/json"`
}

func (u *UpdateEnvironmentRecordRequest) GetTwinID() string {
	if u == nil {
		return ""
	}
	return u.TwinID
}

func (u *UpdateEnvironmentRecordRequest) GetResource() string {
	if u == nil {
		return ""
	}
	return u.Resource
}

func (u *UpdateEnvironmentRecordRequest) GetExternalID() string {
	if u == nil {
		return ""
	}
	return u.ExternalID
}

func (u *UpdateEnvironmentRecordRequest) GetBody() components.UpdateEnvironmentRecordRequest {
	if u == nil {
		return components.UpdateEnvironmentRecordRequest{}
	}
	return u.Body
}

type UpdateEnvironmentRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EnvironmentRecordResponse *components.EnvironmentRecordResponse
}

func (u UpdateEnvironmentRecordResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateEnvironmentRecordResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateEnvironmentRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateEnvironmentRecordResponse) GetEnvironmentRecordResponse() *components.EnvironmentRecordResponse {
	if u == nil {
		return nil
	}
	return u.EnvironmentRecordResponse
}
