// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 20d9382a7dff

package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/panoratech/twinbay-cli/internal/cli"
	"github.com/panoratech/twinbay-cli/internal/clierrors"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

const (
	usage            = "usage: gendocs [output-dir]"
	usageDescription = "Writes the CLI's Cobra markdown command docs into output-dir (default ./docs)."
	readmeAuthStart  = "<!-- Start Authentication [security] -->"
	readmeAuthEnd    = "<!-- End Authentication [security] -->"
)

const readmeAuthentication = `<!-- Start Authentication [security] -->
## Authentication

### Browser login (recommended for workstations)

Sign in with WorkOS AuthKit. The CLI opens a browser, displays the verification
URL and user code as a fallback, and stores the renewable session only in the OS
keychain:

` + "```bash" + `
twinbay auth login
twinbay auth whoami
` + "```" + `

For a headless host, keep the browser closed and follow the printed URL and code:

` + "```bash" + `
twinbay auth login --no-browser
` + "```" + `

Switch the active organization by Twinbay ID, WorkOS ID, or exact name, then end
the remote session and clear local credentials when finished:

` + "```bash" + `
twinbay auth switch <organization>
twinbay auth logout
` + "```" + `

Browser sessions require an available macOS Keychain, Linux Secret Service, or
Windows Credential Locker. They never fall back to the config file.

### API keys for CI and noninteractive use

API-key flags and environment variables do not open a browser or read the
keychain. An explicit API key takes precedence over a stored browser session,
and each request sends exactly one authentication header.

` + "```bash" + `
export CLI_TWINBAY_ORGANIZATION_API_KEY="..."
twinbay --no-interactive api-keys list
` + "```" + `

Credentials may also be passed directly to a command:

` + "```bash" + `
twinbay --organization-api-key "$CLI_TWINBAY_ORGANIZATION_API_KEY" api-keys list
` + "```" + `

Supported environment variables:

| Variable | Description |
|----------|-------------|
| ` + "`CLI_TWINBAY_ACCESS_TOKEN`" + ` | Access token issued by WorkOS AuthKit. |
| ` + "`CLI_TWINBAY_ORGANIZATION_API_KEY`" + ` | An organization API key. Create one at https://console.twinbay.ai/api-keys |

The interactive ` + "`configure`" + ` command remains available for direct credentials and
non-secret settings:

` + "```bash" + `
twinbay configure
` + "```" + `

Configuration is stored in ` + "`~/.config/twinbay/config.yaml`" + `.
<!-- End Authentication [security] -->`

var usageLines = []string{usage, usageDescription}

func main() {
	dir, showHelp, exitCode, messages := parseArgs(os.Args[1:])
	for _, message := range messages {
		fmt.Fprintln(os.Stderr, message)
	}
	if exitCode != 0 {
		os.Exit(exitCode)
	}
	if showHelp {
		return
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		log.Fatal(err)
	}

	rootCmd, err := cli.NewRootCommand()
	if err != nil {
		log.Fatal(err)
	}

	// Exclude cobra's builtin help and completion commands from the generated
	// docs. A generated command may legitimately be named "help" or
	// "completion" (via name overrides); such commands always carry a
	// speakeasy_operation or speakeasy_cli_group annotation and must be kept.
	for _, c := range rootCmd.Commands() {
		if c.Name() != "help" && c.Name() != "completion" {
			continue
		}
		if c.Annotations["speakeasy_operation"] == "" && c.Annotations["speakeasy_cli_group"] == "" {
			rootCmd.RemoveCommand(c)
		}
	}

	// Truncate any command names that would cause filenames to exceed OS limits.
	// Cobra doc generates filenames from the full command path joined with "_".
	truncateLongCommandNames(rootCmd, 0)

	if err := genMarkdownTreeNoDate(rootCmd, dir); err != nil {
		log.Fatal(err)
	}
	if filepath.Clean(dir) == filepath.Clean("./docs") {
		if err := updateReadmeAuthentication("README.md"); err != nil {
			log.Fatal(err)
		}
	}
}

func updateReadmeAuthentication(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read README: %w", err)
	}
	updated, err := replaceReadmeAuthentication(string(content))
	if err != nil {
		return err
	}
	if updated == string(content) {
		return nil
	}
	if err := os.WriteFile(path, []byte(updated), 0644); err != nil {
		return fmt.Errorf("write README: %w", err)
	}
	return nil
}

func replaceReadmeAuthentication(content string) (string, error) {
	start := strings.Index(content, readmeAuthStart)
	end := strings.Index(content, readmeAuthEnd)
	if start == -1 || end == -1 || end < start {
		return "", fmt.Errorf("README authentication markers were not found")
	}
	end += len(readmeAuthEnd)
	return content[:start] + readmeAuthentication + content[end:], nil
}

func parseArgs(args []string) (dir string, showHelp bool, exitCode int, messages []string) {
	for _, arg := range args {
		if arg == "-h" || arg == "--help" || arg == "help" {
			return "", true, 0, usageLines
		}
	}

	if len(args) == 0 {
		return "./docs", false, 0, nil
	}

	if len(args) == 1 {
		arg := args[0]
		if strings.HasPrefix(arg, "-") {
			return "", false, 2, append([]string{fmt.Sprintf("unknown flag %q", arg)}, usageLines...)
		}
		return arg, false, 0, nil
	}

	for _, arg := range args {
		if strings.HasPrefix(arg, "-") {
			return "", false, 2, append([]string{fmt.Sprintf("unknown flag %q", arg)}, usageLines...)
		}
	}

	reason := "too many arguments: " + strings.Join(args, " ")
	return "", false, 2, append([]string{reason}, usageLines...)
}

// truncateLongCommandNames walks the command tree and truncates any Use fields
// that would cause the generated doc filename to exceed filesystem limits.
// Cobra constructs filenames as: parent_path + "_" + use + ".md"
func truncateLongCommandNames(cmd *cobra.Command, parentPathLen int) {
	const maxFilenameLen = 240 // well under the 255 limit
	use := strings.SplitN(cmd.Use, " ", 2)[0]

	// Calculate what the filename length would be: parentPath_use.md
	nameLen := parentPathLen + len(use) + len(".md")
	if parentPathLen > 0 {
		nameLen++ // for the "_" separator
	}

	if nameLen > maxFilenameLen && len(use) > 16 {
		available := maxFilenameLen - parentPathLen - len(".md") - 10 // 10 for _hash
		if parentPathLen > 0 {
			available-- // for separator
		}
		if available < 8 {
			available = 8
		}
		hash := sha256.Sum256([]byte(use))
		truncated := use[:available] + fmt.Sprintf("_%x", hash[:4])
		if cmd.Annotations == nil {
			cmd.Annotations = map[string]string{}
		}
		cmd.Annotations["speakeasy_original_name"] = use
		if parts := strings.SplitN(cmd.Use, " ", 2); len(parts) > 1 {
			cmd.Use = truncated + " " + parts[1]
		} else {
			cmd.Use = truncated
		}
		use = truncated
	}

	childPathLen := parentPathLen + len(use)
	if parentPathLen > 0 {
		childPathLen++
	}

	for _, child := range cmd.Commands() {
		truncateLongCommandNames(child, childPathLen)
	}
}

// genMarkdownTreeNoDate generates markdown docs for all commands without the
// "Auto generated by spf13/cobra on <date>" footer that cobra adds, which
// causes unnecessary churn in version control.
func genMarkdownTreeNoDate(cmd *cobra.Command, dir string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := genMarkdownTreeNoDate(c, dir); err != nil {
			return err
		}
	}

	basename := strings.ReplaceAll(cmd.CommandPath(), " ", "_") + ".md"
	filename := filepath.Join(dir, basename)

	var buf bytes.Buffer
	if err := doc.GenMarkdownCustom(cmd, &buf, func(s string) string { return s }); err != nil {
		return err
	}

	content := buf.String()
	if idx := strings.LastIndex(content, "\n###### Auto generated"); idx != -1 {
		content = strings.TrimRight(content[:idx], "\n") + "\n"
	}
	content += machineInterfaceFooter(cmd)

	return os.WriteFile(filename, []byte(content), 0644)
}

func commandRuntimePath(cmd *cobra.Command) string {
	var parts []string
	for cur := cmd; cur != nil; cur = cur.Parent() {
		name := cur.Name()
		if orig, ok := cur.Annotations["speakeasy_original_name"]; ok && orig != "" {
			name = orig
		}
		parts = append([]string{name}, parts...)
	}
	return strings.Join(parts, " ")
}

func machineInterfaceFooter(cmd *cobra.Command) string {
	var b strings.Builder
	if _, ok := cmd.Annotations["speakeasy_operation"]; ok {
		path := commandRuntimePath(cmd)
		b.WriteString("\n### Machine interface\n\n")
		fmt.Fprintf(&b, "* `%s --usage` — this command's flags, defaults and env vars as machine-readable KDL\n", path)
		if cmd.Flags().Lookup("schema") != nil {
			fmt.Fprintf(&b, "* `%s --schema` — the exact JSON Schema of the request body (all `$ref`s bundled)\n", path)
		}
		fmt.Fprintf(&b, "* `%s --dry-run` — preview the request without OS-keychain access or a network call (human preview on stderr)\n", path)
		b.WriteString("* `--dry-run --output-format json` (or a caller-explicit `--jq`) writes one preview object per request as NDJSON on stdout; jq is not applied to previews\n")
		if cmd.Flags().Lookup("output-file") != nil {
			b.WriteString("* `--output-format json` or `--jq <expr>` for machine-readable live output when the response is JSON; a binary response body is written raw to stdout (use `--output-file <path>` or `--output-b64`); in agent mode errors are a JSON envelope on stderr\n")
		} else {
			b.WriteString("* `--output-format json` or `--jq <expr>` for machine-readable live output; in agent mode errors are a JSON envelope on stderr\n")
		}
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, clierrors.HelpFooter)
	return b.String()
}
