// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 91908b706920

package evaluators

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitIntentEvaluatorsCreate(parent *cobra.Command) error {
	cmd := &cobra.Command{
		Use:     "create",
		Short:   "Create an evaluator and wait",
		Long:    "Compile a test into request matchers and wait until the evaluator is ready. When test-version is omitted, creation pins the latest test version. Use --async to return the queued evaluator immediately.",
		Example: "  twinbay evaluators create --test-id 7ef34f0b-0ae6-4e26-ae92-f49d239d4d7d --twins stripe\n  twinbay evaluators create --test-id 7ef34f0b-0ae6-4e26-ae92-f49d239d4d7d --test-version 3 --twins stripe",
		Args:    cobra.NoArgs,
		RunE:    runIntentEvaluatorsCreateCmd,
		Annotations: map[string]string{
			"speakeasy_operation":            "create_evaluator",
			flagutil.AnnotationWholeBodyFlag: "body",
			"speakeasy_strict_body_keys":     "true",
			"speakeasy_help_defaults":        "omitting test-version pins the latest version at creation",
			"speakeasy_help_escalate":        "full request control via twinbay evaluators enqueue",
			"speakeasy_command_hints":        "{\"CLI_ASYNC_FAILED\":[\"Inspect last_error in the terminal response.\"],\"CLI_ASYNC_TIMEOUT\":[\"Resume with evaluators retrieve and the returned id.\"]}",
			"speakeasy_async":                "{\"idPointer\":\"/id\",\"statePointer\":\"/status\",\"states\":{\"error\":\"failure\",\"pending\":\"pending\",\"ready\":\"success\",\"running\":\"pending\"},\"errorField\":\"last_error\",\"interval\":\"1s\",\"backoff\":1.5,\"maxInterval\":\"10s\",\"timeout\":\"30m\",\"command\":\"evaluators create\",\"resume\":\"twinbay evaluators retrieve --evaluator-id\",\"parameterIn\":\"path\",\"parameterName\":\"evaluator_id\",\"params\":[]}",
		},
	}
	flagutil.RegisterFlags(cmd, enqueueCmdMeta)
	flagutil.SetMetaPromptOptional(cmd, enqueueCmdMeta, false)
	flagutil.ClearBodyRequirements(cmd, enqueueCmdMeta, "")
	cmd.Flags().String("body", "", "Request body as JSON (advanced; replaces intent arguments). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	if err := flagutil.AnnotateBodyFields(cmd, enqueueCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for intent evaluators-create: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	cmd.Flags().Bool("async", false, "Return the operation handle without waiting for a terminal response")
	cmd.Flags().String("poll-interval", "", "Override the initial polling interval (positive Go duration, for example 500ms or 2s)")
	cmd.Flags().String("poll-timeout", "", "Override the overall polling deadline (positive Go duration, at least the effective poll interval)")
	_ = flagutil.AnnotatePromptFlag(cmd, "async", flagutil.PromptFlagSpec{Kind: "bool"})
	_ = flagutil.AnnotatePromptFlag(cmd, "poll-interval", flagutil.PromptFlagSpec{Kind: "string"})
	_ = flagutil.AnnotatePromptFlag(cmd, "poll-timeout", flagutil.PromptFlagSpec{Kind: "string"})
	for _, sibling := range parent.Commands() {
		if sibling.Name() == cmd.Name() || sibling.HasAlias(cmd.Name()) {
			return fmt.Errorf("intent command %q collides with the name or alias of an existing %q command; rename the declared command", "evaluators-create", sibling.Name())
		}
	}
	parent.AddCommand(cmd)
	return nil
}

func runIntentEvaluatorsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "create_evaluator")
	}
	bodySurfaces := []string{"body"}
	for _, surface := range bodySurfaces {
		if flagutil.FlagChanged(cmd, surface) {
			if err := flagutil.ResolveBodyFlag(cmd, surface); err != nil {
				return err
			}
		}
	}
	suppliedBodyFlag := ""
	if flagutil.FlagChanged(cmd, "body") {
		suppliedBodyFlag = "body"
	}
	bodySupplied := suppliedBodyFlag != ""
	if !bodySupplied {
		attached, err := flagutil.AttachStdinBody(cmd, "body")
		if err != nil {
			return err
		}
		bodySupplied = attached
	}
	if !bodySupplied {
		body := map[string]any{}
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		if err := cmd.Flags().Set("body", string(encoded)); err != nil {
			return err
		}
	}
	if err := output.ValidateAsyncFlags(cmd); err != nil {
		return err
	}
	res, err := executeEnqueueCmd(cmd, nil, true)
	if err != nil {
		return err
	}
	if client.IsDryRun(cmd) {
		return nil
	}
	return output.AsyncResult(cmd, res, newPollIntentEvaluatorsCreate)
}
func newPollIntentEvaluatorsCreate(cmd *cobra.Command, id string, params []output.AsyncParameter) (output.AsyncPollFunc, error) {
	request := &operations.GetEvaluatorRequest{}
	if err := flagutil.SetRequestParameter(request, "retrieve", "path", "evaluator_id", id); err != nil {
		return nil, err
	}
	for _, param := range params {
		if err := flagutil.SetRequestParameter(request, "retrieve", param.In, param.Name, param.Value); err != nil {
			return nil, err
		}
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return nil, err
	}
	return func(ctx context.Context) (interface{}, error) {
		res, err := s.Evaluators.Retrieve(ctx, *request, sdkOpts...)
		if err != nil {
			return nil, err
		}
		return res, nil
	}, nil
}
