// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 562091257d40

package evaluators

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listCmdMeta = []flagutil.FlagMeta{
	{FlagName: "test", FieldPath: "Test", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "test-version", FieldPath: "TestVersion", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=test_version"`, Description: "integer value"},
	{FlagName: "page", Shorthand: "p", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 1, HasMinimum: true, Minimum: 1, Description: "Page number"},
	{FlagName: "size", Shorthand: "s", FieldPath: "Size", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, HasMinimum: true, Minimum: 1, HasMaximum: true, Maximum: 100, Description: "Page size"},
}

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List evaluators",
		Long:    "Lists every compilation for a test, optionally filtered by version.",
		Example: "  twinbay evaluators list --test b1ca31c4-0107-480e-a3ad-308c55b0b0e7",
		Args:    cobra.NoArgs,
		RunE:    runListCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "list_evaluators",
		},
	}
	flagutil.RegisterFlags(cmd, listCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListEvaluatorsRequest](listCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list: %w", err)
	}
	cmd.Flags().BoolP("all", "a", false, "Automatically paginate and fetch all results (streams NDJSON for JSON output)")
	cmd.Flags().Int("max-pages", 0, "Maximum number of pages to fetch when using --all (0 = no limit)")
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	allPages, _ := flagutil.GetBoolFlag(cmd, "all")
	maxPages, _ := flagutil.GetIntFlag(cmd, "max-pages")
	if maxPages < 0 {
		return flagutil.WithCLIValidation(fmt.Errorf("--max-pages must be zero or greater"))
	}
	if flagutil.FlagChanged(cmd, "max-pages") && !allPages {
		return flagutil.WithCLIValidation(fmt.Errorf("--max-pages requires --all"))
	}
	req, err := flagutil.BuildRequest[operations.ListEvaluatorsRequest](cmd, listCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if allPages && !client.IsDryRun(cmd) {
		res, err := s.Evaluators.List(cmd.Context(), *req, sdkOpts...)
		if err != nil {
			return output.Error(cmd, err)
		}
		return output.PaginatedResult(cmd, res, "PageEvaluatorResponse", "Items", maxPages, output.PaginationProbe{
			Type:       "offsetLimit",
			CursorKind: "",
			NextCursor: "",
			NextURL:    "",
			Results:    "$.items",
			HasLimit:   true,
		})
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Evaluators.List(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
