// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package logs

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitLogsRoot(parent *cobra.Command) error {
	var LogsCmd = &cobra.Command{
		Use:         "logs",
		Short:       "Operations for logs",
		Long:        "Operations for logs",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(LogsCmd); err != nil {
		return err
	}

	if err := initGetCmd(LogsCmd); err != nil {
		return err
	}

	parent.AddCommand(LogsCmd)
	return nil
}
