// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environments

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var retrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "environment-id", Shorthand: "e", FieldPath: "EnvironmentID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initRetrieveCmd initializes the retrieve command.
func initRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "retrieve",
		Short:   "Retrieve an environment",
		Long:    "Retrieve an environment",
		Example: "  twinbay environments retrieve --environment-id 7a198bae-ee3a-4422-ac59-70a2f11b3b96",
		Args:    cobra.NoArgs,
		RunE:    runRetrieveCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "get_environment",
		},
	}
	flagutil.RegisterFlags(cmd, retrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetEnvironmentRequest](retrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRetrieveCmd executes the retrieve command.
func runRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.GetEnvironmentRequest](cmd, retrieveCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Environments.Retrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
