// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environments

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitEnvironmentsRoot(parent *cobra.Command) error {
	var EnvironmentsCmd = &cobra.Command{
		Use:         "environments",
		Short:       "Create and edit isolated provider environments",
		Long:        "Create and edit isolated provider environments. Each environment contains behavioural twins from the `twins` package.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initCreateCmd(EnvironmentsCmd); err != nil {
		return err
	}

	if err := initListCmd(EnvironmentsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(EnvironmentsCmd); err != nil {
		return err
	}

	parent.AddCommand(EnvironmentsCmd)
	return nil
}
