// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environmenttwins

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var collectCredentialCmdMeta = []flagutil.FlagMeta{
	{FlagName: "environment-id", FieldPath: "EnvironmentID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment-twin-id", FieldPath: "EnvironmentTwinID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initCollectCredentialCmd initializes the collect-credential command.
func initCollectCredentialCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "collect-credential",
		Short:   "Collect the twin's API key",
		Long:    "Returns the key once. A second call is refused.",
		Example: "  twinbay environment-twins collect-credential --environment-id 82039d56-bcef-4032-8747-2d336ff541c0 --environment-twin-id 239718c7-8988-47de-99fd-f55463367d54",
		Args:    cobra.NoArgs,
		RunE:    runCollectCredentialCmd,
		Aliases: []string{"cc"},
		Annotations: map[string]string{
			"speakeasy_operation": "collect_environment_twin_credential",
		},
	}
	flagutil.RegisterFlags(cmd, collectCredentialCmdMeta)
	if err := flagutil.ValidateMeta[operations.CollectEnvironmentTwinCredentialRequest](collectCredentialCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for collect-credential: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runCollectCredentialCmd executes the collect-credential command.
func runCollectCredentialCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.CollectEnvironmentTwinCredentialRequest](cmd, collectCredentialCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.EnvironmentTwins.CollectCredential(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
