// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environmenttwins

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitEnvironmentTwinsRoot(parent *cobra.Command) error {
	var EnvironmentTwinsCmd = &cobra.Command{
		Use:         "environment-twins",
		Short:       "Operations for environment-twins",
		Long:        "Operations for environment-twins",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"etw"},
	}

	if err := initRetrieveCmd(EnvironmentTwinsCmd); err != nil {
		return err
	}

	if err := initStartCmd(EnvironmentTwinsCmd); err != nil {
		return err
	}

	if err := initStopCmd(EnvironmentTwinsCmd); err != nil {
		return err
	}

	if err := initCollectCredentialCmd(EnvironmentTwinsCmd); err != nil {
		return err
	}

	if err := initAdvanceCmd(EnvironmentTwinsCmd); err != nil {
		return err
	}

	parent.AddCommand(EnvironmentTwinsCmd)
	return nil
}
