// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sandboxrecords

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitSandboxRecordsRoot(parent *cobra.Command) error {
	var SandboxRecordsCmd = &cobra.Command{
		Use:         "sandbox-records",
		Short:       "Operations for sandbox-records",
		Long:        "Operations for sandbox-records",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"sr"},
	}

	if err := initListCmd(SandboxRecordsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(SandboxRecordsCmd); err != nil {
		return err
	}

	parent.AddCommand(SandboxRecordsCmd)
	return nil
}
