// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/interactive"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listVersionsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "test-id", Shorthand: "t", FieldPath: "TestID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "page", Shorthand: "p", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 1, HasMinimum: true, Minimum: 1, Description: "Page number"},
	{FlagName: "size", Shorthand: "s", FieldPath: "Size", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, HasMinimum: true, Minimum: 1, HasMaximum: true, Maximum: 100, Description: "Page size"},
}

// initListVersionsCmd initializes the list-versions command.
func initListVersionsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-versions [test-id]",
		Short:   "List a test's versions",
		Long:    "List a test's versions",
		Example: "  twinbay tests list-versions --test-id 8ca5e633-292b-437b-bb16-096839c97d14",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runListVersionsCmd,
		Aliases: []string{"lv"},
		Annotations: map[string]string{
			"speakeasy_operation": "list_test_versions",
		},
	}
	flagutil.RegisterFlags(cmd, listVersionsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListTestVersionsRequest](listVersionsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-versions: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "test-id", "string value (or pass it as the [test-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "test-id", Summary: "string value", Required: true, SatisfiedBy: []string{"test-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for list-versions: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListVersionsCmd executes the list-versions command.
func runListVersionsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.ListTestVersionsRequest](cmd, listVersionsCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Tests.ListVersions(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
