// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 40ef83c5cff7

package tests

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTestsRoot(parent *cobra.Command) error {
	var TestsCmd = &cobra.Command{
		Use:         "tests",
		Short:       "Outcomes described in natural language, compiled once into request matchers, and evaluated deterministically against the traffic an attempt was served",
		Long:        "Outcomes described in natural language, compiled once into request matchers, and evaluated deterministically against the traffic an attempt was served.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initCreateCmd(TestsCmd); err != nil {
		return err
	}

	if err := initListCmd(TestsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(TestsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(TestsCmd); err != nil {
		return err
	}

	if err := initListVersionsCmd(TestsCmd); err != nil {
		return err
	}

	if err := initRetrieveVersionCmd(TestsCmd); err != nil {
		return err
	}

	parent.AddCommand(TestsCmd)
	return nil
}
