// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/config"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initWhoamiCmd initializes the whoami command.
func initWhoamiCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:   "whoami",
		Short: "Display current authentication configuration",
		Long: `Display the currently configured settings and their sources.

Sources are shown as:
  [flag]    - Set via command line flag
  [env]     - Set via environment variable (CLI_TWINBAY_*)
  [keyring] - Set via OS keychain (stored by configure command)
  [config]  - Set via config file (~/.config/twinbay/config.yaml)
  [unset]   - Not configured

Credential values are masked for security.`,
		Args: cobra.NoArgs,
		RunE: runWhoamiCmd,
	}
	parent.AddCommand(cmd)
	return nil
}

// runWhoamiCmd executes the whoami command.
func runWhoamiCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}

	if output.IsMachineMode(cmd) {
		info := map[string]any{
			"config_file":        config.GetConfigPath(),
			"environment_prefix": "CLI_TWINBAY_",
		}
		credentials := map[string]any{}
		{
			value, source := config.ResolveSecurityCredential(cmd, "organization-api-key")
			credentials["organization-api-key"] = map[string]any{"source": source, "value": maskSecret(value)}
		}
		info["credentials"] = credentials

		return output.LocalResult(cmd, info)
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "Configuration")
	fmt.Fprintln(out, "=============")
	fmt.Fprintln(out)
	fmt.Fprintf(out, "Config file: %s\n", config.GetConfigPath())
	fmt.Fprintf(out, "Environment prefix: CLI_TWINBAY_\n")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Credentials:")

	// An organization API key, as minted by POST /organizations/current/api-keys.
	{
		value, source := config.ResolveSecurityCredential(cmd, "organization-api-key")
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "organization-api-key", source, maskSecret(value))
	}

	return nil
}
