// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var renameCurrentOrganizationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, MinLength: 1, Description: "New display name of the organization [required]"},
}

// initRenameCurrentOrganizationCmd initializes the rename-current-organization command.
func initRenameCurrentOrganizationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "rename-current",
		Short:   "Rename the active organization",
		Long:    "Requires the **admin** role or above in the active organization.",
		Example: "  twinbay organizations rename-current --name <value>",
		Args:    cobra.NoArgs,
		RunE:    runRenameCurrentOrganizationCmd,
		Aliases: []string{"rcu"},
		Annotations: map[string]string{
			"speakeasy_operation": "rename_current_organization",
		},
	}
	flagutil.RegisterFlags(cmd, renameCurrentOrganizationCmdMeta)
	if err := flagutil.ValidateMeta[components.UpdateOrganizationRequest](renameCurrentOrganizationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for rename-current-organization: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, renameCurrentOrganizationCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for rename-current-organization: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runRenameCurrentOrganizationCmd executes the rename-current-organization command.
func runRenameCurrentOrganizationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "rename_current_organization")
	}
	request, err := flagutil.BuildRequest[components.UpdateOrganizationRequest](cmd, renameCurrentOrganizationCmdMeta, "", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organizations.RenameCurrentOrganization(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
