// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitOrganizationsRoot(parent *cobra.Command) error {
	var OrganizationsCmd = &cobra.Command{
		Use:         "organizations",
		Short:       "Organizations the caller belongs to",
		Long:        "Organizations the caller belongs to. Every authenticated request acts inside exactly one organization — the one its access token names — so these routes address it as `current`.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListOrganizationsCmd(OrganizationsCmd); err != nil {
		return err
	}

	if err := initCreateOrganizationCmd(OrganizationsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(OrganizationsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(OrganizationsCmd); err != nil {
		return err
	}

	parent.AddCommand(OrganizationsCmd)
	return nil
}
