// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package users

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitUsersRoot(parent *cobra.Command) error {
	var UsersCmd = &cobra.Command{
		Use:         "users",
		Short:       "The current user",
		Long:        "The current user. Sign-up and sign-in happen in WorkOS AuthKit, which issues the access tokens this API accepts.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initReadMeCmd(UsersCmd); err != nil {
		return err
	}

	parent.AddCommand(UsersCmd)
	return nil
}
