// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package testversions

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTestVersionsRoot(parent *cobra.Command) error {
	var TestVersionsCmd = &cobra.Command{
		Use:         "test-versions",
		Short:       "Operations for test-versions",
		Long:        "Operations for test-versions",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"tv"},
	}

	if err := initCreateCmd(TestVersionsCmd); err != nil {
		return err
	}

	if err := initListCmd(TestVersionsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(TestVersionsCmd); err != nil {
		return err
	}

	parent.AddCommand(TestVersionsCmd)
	return nil
}
