// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sandboxtemplates

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var deleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "template-id", Shorthand: "t", FieldPath: "TemplateID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initDeleteCmd initializes the delete command.
func initDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete a sandbox template",
		Long:    "Sandboxes already started from it are untouched.",
		Example: "  twinbay sandbox-templates delete --template-id a20706ee-1743-41a5-b94e-257617129b0a",
		Args:    cobra.NoArgs,
		RunE:    runDeleteCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "delete_sandbox_template",
		},
	}
	flagutil.RegisterFlags(cmd, deleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteSandboxTemplateRequest](deleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteCmd executes the delete command.
func runDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.DeleteSandboxTemplateRequest](cmd, deleteCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SandboxTemplates.Delete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
