// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environmentlogs

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitEnvironmentLogsRoot(parent *cobra.Command) error {
	var EnvironmentLogsCmd = &cobra.Command{
		Use:         "environment-logs",
		Short:       "Operations for environment-logs",
		Long:        "Operations for environment-logs",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"el"},
	}

	if err := initListCmd(EnvironmentLogsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(EnvironmentLogsCmd); err != nil {
		return err
	}

	parent.AddCommand(EnvironmentLogsCmd)
	return nil
}
