// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6eb0821e2d4b

package billing

import (
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initDowngradeCmd initializes the downgrade command.
func initDowngradeCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "downgrade",
		Short:   "Downgrade to Free",
		Long:    "New seed and test generation stops at once, and every live environment gets the Free plan's deadline, counted from now. Requires the **admin** role.",
		Example: "  twinbay billing downgrade",
		Args:    cobra.NoArgs,
		RunE:    runDowngradeCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "downgrade_billing_plan",
		},
	}
	parent.AddCommand(cmd)
	return nil
}

// runDowngradeCmd executes the downgrade command.
func runDowngradeCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Billing.Downgrade(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
