// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 97c0c6875ca8

package billing

import (
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initRetrievePaymentMethodCmd initializes the retrieve-payment-method command.
func initRetrievePaymentMethodCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "retrieve-payment-method",
		Short:   "Read the payment method",
		Long:    "The card pay as you go charges, or null when none is saved.",
		Example: "  twinbay billing retrieve-payment-method",
		Args:    cobra.NoArgs,
		RunE:    runRetrievePaymentMethodCmd,
		Aliases: []string{"rpm"},
		Annotations: map[string]string{
			"speakeasy_operation": "read_payment_method",
		},
	}
	parent.AddCommand(cmd)
	return nil
}

// runRetrievePaymentMethodCmd executes the retrieve-payment-method command.
func runRetrievePaymentMethodCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Billing.RetrievePaymentMethod(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
