// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e4d7cba42048

package billing

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitBillingRoot(parent *cobra.Command) error {
	var BillingCmd = &cobra.Command{
		Use:         "billing",
		Short:       "The active organization's plan, its limits, and what the current period has cost so far",
		Long:        "The active organization's plan, its limits, and what the current period has cost so far.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initRetrieveCmd(BillingCmd); err != nil {
		return err
	}

	if err := initListInvoicesCmd(BillingCmd); err != nil {
		return err
	}

	if err := initRetrievePaymentMethodCmd(BillingCmd); err != nil {
		return err
	}

	if err := initCheckoutCmd(BillingCmd); err != nil {
		return err
	}

	if err := initUpgradeCmd(BillingCmd); err != nil {
		return err
	}

	if err := initDowngradeCmd(BillingCmd); err != nil {
		return err
	}

	parent.AddCommand(BillingCmd)
	return nil
}
