// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sandboxtwins

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var retrieveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "sandbox-id", FieldPath: "SandboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "sandbox-twin-id", FieldPath: "SandboxTwinID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "wait-for", Shorthand: "w", FieldPath: "WaitFor", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=wait_for"`, Description: "options: ready, stopped"},
}

// initRetrieveCmd initializes the retrieve command.
func initRetrieveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "retrieve",
		Short:   "Retrieve a sandbox twin",
		Long:    "With `wait_for`, the answer is held until the twin reaches that state, a run of it settles, or the wait runs out — so a caller waiting for a twin to serve sends one request rather than polling.",
		Example: "  twinbay sandbox-twins retrieve --sandbox-id eabe4821-32dd-4700-bca8-499c792546b5 --sandbox-twin-id e3de5d93-78fe-4214-8eef-52bf8c788302",
		Args:    cobra.NoArgs,
		RunE:    runRetrieveCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "get_sandbox_twin",
		},
	}
	flagutil.RegisterFlags(cmd, retrieveCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetSandboxTwinRequest](retrieveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for retrieve: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRetrieveCmd executes the retrieve command.
func runRetrieveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.GetSandboxTwinRequest](cmd, retrieveCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SandboxTwins.Retrieve(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
