// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sandboxtwins

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var startCmdMeta = []flagutil.FlagMeta{
	{FlagName: "sandbox-id", FieldPath: "SandboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "sandbox-twin-id", FieldPath: "SandboxTwinID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initStartCmd initializes the start command.
func initStartCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "start",
		Short:   "Start a sandbox twin",
		Long:    "Queues a fresh container. Its state and credentials are new.",
		Example: "  twinbay sandbox-twins start --sandbox-id 6487b8fc-9461-4e43-92a9-daf1ccba9d95 --sandbox-twin-id 63cbc00d-b389-49c5-a459-8c61543273fd",
		Args:    cobra.NoArgs,
		RunE:    runStartCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "start_sandbox_twin",
		},
	}
	flagutil.RegisterFlags(cmd, startCmdMeta)
	if err := flagutil.ValidateMeta[operations.StartSandboxTwinRequest](startCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for start: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runStartCmd executes the start command.
func runStartCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.StartSandboxTwinRequest](cmd, startCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SandboxTwins.Start(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
