// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package evaluatorversions

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitEvaluatorVersionsRoot(parent *cobra.Command) error {
	var EvaluatorVersionsCmd = &cobra.Command{
		Use:         "evaluator-versions",
		Short:       "Operations for evaluator-versions",
		Long:        "Operations for evaluator-versions",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ev"},
	}

	if err := initCreateCmd(EvaluatorVersionsCmd); err != nil {
		return err
	}

	if err := initListCmd(EvaluatorVersionsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(EvaluatorVersionsCmd); err != nil {
		return err
	}

	parent.AddCommand(EvaluatorVersionsCmd)
	return nil
}
