// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package main

import (
	"errors"
	"fmt"
	"os"

	"github.com/panoratech/twinbay-cli/internal/cli"
	"github.com/panoratech/twinbay-cli/internal/clierrors"
)

// version and buildTime can be set at build time using Go linker flags:
//
//	go build -ldflags "-X main.version=x.y.z -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" ./cmd/twinbay
var version string
var buildTime string

func main() {
	if version != "" {
		cli.Version = version
	}
	if buildTime != "" {
		cli.BuildTime = buildTime
	}

	if err := cli.Execute(); err != nil {
		var rendered interface{ Rendered() bool }
		if !errors.As(err, &rendered) || !rendered.Rendered() {
			fmt.Fprintln(os.Stderr, err)
		}
		os.Exit(clierrors.ExitCode(err))
	}
}
