// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package evaluations

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/interactive"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listCmdMeta = []flagutil.FlagMeta{
	{FlagName: "test-run-id", Shorthand: "t", FieldPath: "TestRunID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "page", Shorthand: "p", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 1, HasMinimum: true, Minimum: 1, Description: "Page number"},
	{FlagName: "size", Shorthand: "s", FieldPath: "Size", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, HasMinimum: true, Minimum: 1, HasMaximum: true, Maximum: 100, Description: "Page size"},
}

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list [test-run-id]",
		Short:   "List a test run's evaluations",
		Long:    "List a test run's evaluations",
		Example: "  twinbay evaluations list --test-run-id f8b780a1-5b61-4c3c-b857-7812912f82c1",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runListCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "list_evaluations",
		},
	}
	flagutil.RegisterFlags(cmd, listCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListEvaluationsRequest](listCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list: %w", err)
	}
	cmd.Flags().BoolP("all", "a", false, "Automatically paginate and fetch all results (streams NDJSON for JSON output)")
	cmd.Flags().Int("max-pages", 0, "Maximum number of pages to fetch when using --all (0 = no limit)")
	if err := flagutil.DeclarePositionalFlag(cmd, "test-run-id", "string value (or pass it as the [test-run-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "test-run-id", Summary: "string value", Required: true, SatisfiedBy: []string{"test-run-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	allPages, _ := flagutil.GetBoolFlag(cmd, "all")
	maxPages, _ := flagutil.GetIntFlag(cmd, "max-pages")
	if maxPages < 0 {
		return flagutil.WithCLIValidation(fmt.Errorf("--max-pages must be zero or greater"))
	}
	if flagutil.FlagChanged(cmd, "max-pages") && !allPages {
		return flagutil.WithCLIValidation(fmt.Errorf("--max-pages requires --all"))
	}
	req, err := flagutil.BuildRequest[operations.ListEvaluationsRequest](cmd, listCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if allPages && !client.IsDryRun(cmd) {
		res, err := s.Evaluations.List(cmd.Context(), *req, sdkOpts...)
		if err != nil {
			return output.Error(cmd, err)
		}
		return output.PaginatedResult(cmd, res, "PageEvaluationResponse", "Items", maxPages, output.PaginationProbe{
			Type:       "offsetLimit",
			CursorKind: "",
			NextCursor: "",
			NextURL:    "",
			Results:    "$.items",
			HasLimit:   true,
		})
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Evaluations.List(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
