// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package evaluations

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitEvaluationsRoot(parent *cobra.Command) error {
	var EvaluationsCmd = &cobra.Command{
		Use:         "evaluations",
		Short:       "Operations for evaluations",
		Long:        "Operations for evaluations",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initCreateCmd(EvaluationsCmd); err != nil {
		return err
	}

	if err := initListCmd(EvaluationsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(EvaluationsCmd); err != nil {
		return err
	}

	if err := initRegradeCmd(EvaluationsCmd); err != nil {
		return err
	}

	parent.AddCommand(EvaluationsCmd)
	return nil
}
