// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package scenarios

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/interactive"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var deleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "scenario-id", Shorthand: "s", FieldPath: "ScenarioID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initDeleteCmd initializes the delete command.
func initDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete [scenario-id]",
		Short:   "Delete a scenario",
		Long:    "Referenced seeds and environments already started from it are untouched.",
		Example: "  twinbay scenarios delete --scenario-id 285fac7d-f7d1-4892-b58f-40835c7aeb4a",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runDeleteCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "delete_scenario",
		},
	}
	flagutil.RegisterFlags(cmd, deleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteScenarioRequest](deleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "scenario-id", "string value (or pass it as the [scenario-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "scenario-id", Summary: "string value", Required: true, SatisfiedBy: []string{"scenario-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteCmd executes the delete command.
func runDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.DeleteScenarioRequest](cmd, deleteCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Scenarios.Delete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
