// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package scenarios

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitScenariosRoot(parent *cobra.Command) error {
	var ScenariosCmd = &cobra.Command{
		Use:         "scenarios",
		Short:       "Reusable starting setups of provider twins and optional seeds",
		Long:        "Reusable starting setups of provider twins and optional seeds.",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initCreateCmd(ScenariosCmd); err != nil {
		return err
	}

	if err := initListCmd(ScenariosCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(ScenariosCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(ScenariosCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(ScenariosCmd); err != nil {
		return err
	}

	parent.AddCommand(ScenariosCmd)
	return nil
}
