// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9336fbd805f9

package seeds

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var enqueueCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, MinLength: 1, Description: "Display name of the seed [required]"},
	{FlagName: "twin", Shorthand: "t", FieldPath: "Twin", Kind: flagutil.FlagKindString, Required: true, MinLength: 1, Description: "Slug of the twin this seed is for [required]"},
	{FlagName: "prompt", Shorthand: "p", FieldPath: "Prompt", Kind: flagutil.FlagKindString, Required: true, MinLength: 1, Description: "The starting state you want, in your own words. \"50 open tickets, half of them aging past 90 days.\" [required]"},
}

// initEnqueueCmd initializes the enqueue command.
func initEnqueueCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "enqueue",
		Short:   "Generate a seed",
		Long:    "Describes the starting state you want and answers immediately; a worker expands it into rows. Read the seed until it is `ready`, then pass its id as a twin's `seed` when you create an environment.",
		Example: "",
		Args:    cobra.NoArgs,
		RunE:    runEnqueueCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "create_seed",
		},
	}
	flagutil.RegisterFlags(cmd, enqueueCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateSeedRequest](enqueueCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for enqueue: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, enqueueCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for enqueue: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runEnqueueCmd executes the enqueue command.
func runEnqueueCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "create_seed")
	}
	res, err := executeEnqueueCmd(cmd, args, false)
	if err != nil {
		return err
	}
	if res == nil {
		return nil
	}
	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
func executeEnqueueCmd(cmd *cobra.Command, args []string, asyncIntent bool) (*operations.CreateSeedResponse, error) {
	request, err := flagutil.BuildRequest[components.CreateSeedRequest](cmd, enqueueCmdMeta, "", "body")
	if err != nil {
		return nil, flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return nil, err
	}
	if client.IsDryRun(cmd) || asyncIntent {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return nil, err
	}
	if asyncIntent || output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Seeds.Enqueue(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return nil, output.Error(cmd, err)
	}
	return res, nil
}
