// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 82cdb5af907e

package seeds

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/interactive"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
	"strings"
)

func InitIntentSeedsCreate(parent *cobra.Command) error {
	cmd := &cobra.Command{
		Use:     "create [prompt]",
		Short:   "Generate a seed and wait",
		Long:    "Generate a reusable starting state and wait until it is ready. Use --async to return the queued seed immediately.\n\nArguments:\n  <prompt>  Starting state to generate",
		Example: "  twinbay seeds create --name aging-backlog --twin zendesk \"50 open tickets, half aging past 90 days\"",
		Args:    cobra.ArbitraryArgs,
		RunE:    runIntentSeedsCreateCmd,
		Annotations: map[string]string{
			"speakeasy_operation":            "create_seed",
			flagutil.AnnotationWholeBodyFlag: "body",
			"speakeasy_strict_body_keys":     "true",
			"speakeasy_help_escalate":        "full request control via twinbay seeds enqueue",
			"speakeasy_command_hints":        "{\"CLI_ASYNC_FAILED\":[\"Inspect failure in the terminal response.\"],\"CLI_ASYNC_TIMEOUT\":[\"Resume with seeds retrieve and the returned id.\"]}",
			"speakeasy_async":                "{\"idPointer\":\"/id\",\"statePointer\":\"/status\",\"states\":{\"failed\":\"failure\",\"pending\":\"pending\",\"ready\":\"success\",\"running\":\"pending\"},\"interval\":\"1s\",\"backoff\":1.5,\"maxInterval\":\"10s\",\"timeout\":\"2h\",\"command\":\"seeds create\",\"resume\":\"twinbay seeds retrieve --seed-id\",\"parameterIn\":\"path\",\"parameterName\":\"seed_id\",\"params\":[]}",
		},
	}
	flagutil.RegisterFlags(cmd, enqueueCmdMeta)
	flagutil.SetMetaPromptOptional(cmd, enqueueCmdMeta, false)
	flagutil.ClearBodyRequirements(cmd, enqueueCmdMeta, "")
	_ = flagutil.OverridePromptRequirement(cmd, "prompt", false, false)
	cmd.Flags().String("body", "", "Request body as JSON (advanced; replaces intent arguments). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	if err := flagutil.AnnotateBodyFields(cmd, enqueueCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for intent seeds-create: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{
			Name: "prompt", Summary: "Starting state to generate",
			Required: true, Variadic: true,
			BodyKey:     "prompt",
			SatisfiedBy: []string{"prompt", "body"},
		},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for intent seeds-create: %w", err)
	}
	cmd.Flags().Bool("async", false, "Return the operation handle without waiting for a terminal response")
	cmd.Flags().String("poll-interval", "", "Override the initial polling interval (positive Go duration, for example 500ms or 2s)")
	cmd.Flags().String("poll-timeout", "", "Override the overall polling deadline (positive Go duration, at least the effective poll interval)")
	_ = flagutil.AnnotatePromptFlag(cmd, "async", flagutil.PromptFlagSpec{Kind: "bool"})
	_ = flagutil.AnnotatePromptFlag(cmd, "poll-interval", flagutil.PromptFlagSpec{Kind: "string"})
	_ = flagutil.AnnotatePromptFlag(cmd, "poll-timeout", flagutil.PromptFlagSpec{Kind: "string"})
	for _, sibling := range parent.Commands() {
		if sibling.Name() == cmd.Name() || sibling.HasAlias(cmd.Name()) {
			return fmt.Errorf("intent command %q collides with the name or alias of an existing %q command; rename the declared command", "seeds-create", sibling.Name())
		}
	}
	parent.AddCommand(cmd)
	return nil
}

func runIntentSeedsCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "create_seed")
	}
	bodySurfaces := []string{"body"}
	for _, surface := range bodySurfaces {
		if flagutil.FlagChanged(cmd, surface) {
			if err := flagutil.ResolveBodyFlag(cmd, surface); err != nil {
				return err
			}
		}
	}
	suppliedBodyFlag := ""
	if flagutil.FlagChanged(cmd, "body") {
		suppliedBodyFlag = "body"
	}
	bodySupplied := suppliedBodyFlag != ""
	if !bodySupplied {
		attached, err := flagutil.AttachStdinBody(cmd, "body")
		if err != nil {
			return err
		}
		bodySupplied = attached
	}
	if hint := flagutil.SpacedBoolValueHint(cmd, args); hint != "" && !client.IsJSONDryRun(cmd) && !output.IsMachineMode(cmd) {
		fmt.Fprintln(cmd.ErrOrStderr(), hint)
	}
	if bodySupplied {
		if flagutil.FlagChanged(cmd, "prompt") {
			if v, _ := flagutil.GetStringFlag(cmd, "prompt"); v == "" {
				return flagutil.WithCLIValidation(fmt.Errorf("--prompt must not be empty"))
			}
		}
		if len(args) > 0 {
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "prompt", "the <prompt> argument", strings.Join(args, " ")); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
	}
	if len(args) == 0 && !bodySupplied && !flagutil.FlagChanged(cmd, "prompt") && !flagutil.FlagChanged(cmd, "body") {
		return output.UsageHelpError(cmd, fmt.Errorf("%s", "missing required argument <prompt> (or pass a full request with --body)"))
	}
	if !bodySupplied {
		body := map[string]any{}
		if len(args) == 0 && !flagutil.FlagChanged(cmd, "prompt") {
			return flagutil.WithCLIValidation(fmt.Errorf("missing required argument (or pass a full request with --body)"))
		}
		// An explicitly empty backing-flag value must not stand in for the
		// required positional — nor override a supplied one at the request
		// layer — and bypass required-string validation.
		if flagutil.FlagChanged(cmd, "prompt") {
			if v, _ := flagutil.GetStringFlag(cmd, "prompt"); v == "" {
				return flagutil.WithCLIValidation(fmt.Errorf("--prompt must not be empty"))
			}
		}
		if len(args) > 0 {
			body["prompt"] = strings.Join(args, " ")
		}
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		if err := cmd.Flags().Set("body", string(encoded)); err != nil {
			return err
		}
	}
	if err := output.ValidateAsyncFlags(cmd); err != nil {
		return err
	}
	res, err := executeEnqueueCmd(cmd, nil, true)
	if err != nil {
		return err
	}
	if client.IsDryRun(cmd) {
		return nil
	}
	return output.AsyncResult(cmd, res, newPollIntentSeedsCreate)
}
func newPollIntentSeedsCreate(cmd *cobra.Command, id string, params []output.AsyncParameter) (output.AsyncPollFunc, error) {
	request := &operations.GetSeedRequest{}
	if err := flagutil.SetRequestParameter(request, "retrieve", "path", "seed_id", id); err != nil {
		return nil, err
	}
	for _, param := range params {
		if err := flagutil.SetRequestParameter(request, "retrieve", param.In, param.Name, param.Value); err != nil {
			return nil, err
		}
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return nil, err
	}
	return func(ctx context.Context) (interface{}, error) {
		res, err := s.Seeds.Retrieve(ctx, *request, sdkOpts...)
		if err != nil {
			return nil, err
		}
		return res, nil
	}, nil
}
