// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package seeds

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listSuggestionsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "twin", Shorthand: "t", FieldPath: "Twin", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=twin"`, Description: "Only suggestions for this twin's slug."},
	{FlagName: "page", Shorthand: "p", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 1, HasMinimum: true, Minimum: 1, Description: "Page number"},
	{FlagName: "size", Shorthand: "s", FieldPath: "Size", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, HasMinimum: true, Minimum: 1, HasMaximum: true, Maximum: 100, Description: "Page size"},
}

// initListSuggestionsCmd initializes the list-suggestions command.
func initListSuggestionsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-suggestions",
		Short:   "List suggested starting states",
		Long:    "Described states the product ships for each twin that can be seeded. Send one back as a seed's `prompt`, edited or as it stands.",
		Example: "  twinbay seeds list-suggestions",
		Args:    cobra.NoArgs,
		RunE:    runListSuggestionsCmd,
		Aliases: []string{"ls"},
		Annotations: map[string]string{
			"speakeasy_operation": "list_seed_suggestions",
		},
	}
	flagutil.RegisterFlags(cmd, listSuggestionsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListSeedSuggestionsRequest](listSuggestionsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-suggestions: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListSuggestionsCmd executes the list-suggestions command.
func runListSuggestionsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.ListSeedSuggestionsRequest](cmd, listSuggestionsCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Seeds.ListSuggestions(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
