// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d76c733247f9

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type Plan string

const (
	PlanFree  Plan = "free"
	PlanPaygo Plan = "paygo"
)

func (e Plan) ToPointer() *Plan {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Plan) IsExact() bool {
	if e != nil {
		switch *e {
		case "free", "paygo":
			return true
		}
	}
	return false
}

type BillingResponse struct {
	Plan Plan `json:"plan"`
	// How long an environment may run, or null for no limit
	MaxEnvironmentSeconds *int64 `json:"max_environment_seconds"`
	// How many twins may run at once, or null for no limit
	MaxParallelTwins *int64 `json:"max_parallel_twins"`
	// Whether seeds, generated tests and evaluators can be built
	AiGenerationEnabled bool `json:"ai_generation_enabled"`
	// Twins currently asked to run
	ActiveTwins int64 `json:"active_twins"`
	// Whether the billing account is set up; plan changes wait for it
	Ready bool `json:"ready"`
	// Whether this deployment can take a card for pay as you go
	UpgradeAvailable bool `json:"upgrade_available"`
	// Spendable USD credit after current draft invoice deductions. Null while billing is unreachable or not yet set up.
	RemainingCreditCents optionalnullable.OptionalNullable[float64] `json:"remaining_credit_cents,omitzero"`
	// The draft invoice for the current period, updated as usage arrives. Null while billing is unreachable or not yet set up.
	Invoice optionalnullable.OptionalNullable[InvoicePreview] `json:"invoice,omitzero"`
}

func (b BillingResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BillingResponse) GetPlan() Plan {
	if b == nil {
		return Plan("")
	}
	return b.Plan
}

func (b *BillingResponse) GetMaxEnvironmentSeconds() *int64 {
	if b == nil {
		return nil
	}
	return b.MaxEnvironmentSeconds
}

func (b *BillingResponse) GetMaxParallelTwins() *int64 {
	if b == nil {
		return nil
	}
	return b.MaxParallelTwins
}

func (b *BillingResponse) GetAiGenerationEnabled() bool {
	if b == nil {
		return false
	}
	return b.AiGenerationEnabled
}

func (b *BillingResponse) GetActiveTwins() int64 {
	if b == nil {
		return 0
	}
	return b.ActiveTwins
}

func (b *BillingResponse) GetReady() bool {
	if b == nil {
		return false
	}
	return b.Ready
}

func (b *BillingResponse) GetUpgradeAvailable() bool {
	if b == nil {
		return false
	}
	return b.UpgradeAvailable
}

func (b *BillingResponse) GetRemainingCreditCents() optionalnullable.OptionalNullable[float64] {
	if b == nil {
		return nil
	}
	return b.RemainingCreditCents
}

func (b *BillingResponse) GetInvoice() optionalnullable.OptionalNullable[InvoicePreview] {
	if b == nil {
		return nil
	}
	return b.Invoice
}
