// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CompileRequest struct {
	// Catalog slugs of the twins whose APIs the outcomes are about.
	Twins []string `json:"twins"`
}

func (c *CompileRequest) GetTwins() []string {
	if c == nil {
		return []string{}
	}
	return c.Twins
}
