// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 52c213c20475

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type CreatedAPIKeyResponse struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	// When the key stops working, or null when it never does
	ExpiresAt *time.Time   `json:"expires_at"`
	CreatedBy UserResponse `json:"created_by"`
	// The credential itself, to send in the `X-API-Key` header. Only the digest is stored, so this is the only time it is readable.
	Token string `json:"token"`
}

func (c CreatedAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatedAPIKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatedAPIKeyResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreatedAPIKeyResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatedAPIKeyResponse) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreatedAPIKeyResponse) GetExpiresAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CreatedAPIKeyResponse) GetCreatedBy() UserResponse {
	if c == nil {
		return UserResponse{}
	}
	return c.CreatedBy
}

func (c *CreatedAPIKeyResponse) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}
