// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateTestRequest struct {
	TaskDescription string           `json:"task_description"`
	Outcomes        []OutcomeRequest `json:"outcomes"`
	Name            string           `json:"name"`
}

func (c *CreateTestRequest) GetTaskDescription() string {
	if c == nil {
		return ""
	}
	return c.TaskDescription
}

func (c *CreateTestRequest) GetOutcomes() []OutcomeRequest {
	if c == nil {
		return []OutcomeRequest{}
	}
	return c.Outcomes
}

func (c *CreateTestRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
