// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type CreateExportRequest struct {
	// Twin slots inside this environment to export, by `environment_twins.id`. Omitted exports every twin; an empty list would export none, which is never what a caller means.
	EnvironmentTwinIds optionalnullable.OptionalNullable[[]string] `json:"environment_twin_ids,omitzero"`
	// Export calls served at or after this instant.
	OccurredFrom optionalnullable.OptionalNullable[time.Time] `json:"occurred_from,omitzero"`
	// Export calls served at or before this instant. An export never reads past the moment it was asked for, whatever this says.
	OccurredUntil optionalnullable.OptionalNullable[time.Time] `json:"occurred_until,omitzero"`
}

func (c CreateExportRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateExportRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateExportRequest) GetEnvironmentTwinIds() optionalnullable.OptionalNullable[[]string] {
	if c == nil {
		return nil
	}
	return c.EnvironmentTwinIds
}

func (c *CreateExportRequest) GetOccurredFrom() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.OccurredFrom
}

func (c *CreateExportRequest) GetOccurredUntil() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.OccurredUntil
}
