// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateSeedRequest struct {
	// Display name of the seed
	Name string `json:"name"`
	// Slug of the twin this seed is for
	Twin string `json:"twin"`
	// The starting state you want, in your own words. "50 open tickets, half of them aging past 90 days."
	Prompt string `json:"prompt"`
}

func (c *CreateSeedRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSeedRequest) GetTwin() string {
	if c == nil {
		return ""
	}
	return c.Twin
}

func (c *CreateSeedRequest) GetPrompt() string {
	if c == nil {
		return ""
	}
	return c.Prompt
}
