// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CreateEvaluationRequestPhase string

const (
	CreateEvaluationRequestPhaseCheckpoint CreateEvaluationRequestPhase = "checkpoint"
	CreateEvaluationRequestPhaseFinal      CreateEvaluationRequestPhase = "final"
)

func (e CreateEvaluationRequestPhase) ToPointer() *CreateEvaluationRequestPhase {
	return &e
}
func (e *CreateEvaluationRequestPhase) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "checkpoint":
		fallthrough
	case "final":
		*e = CreateEvaluationRequestPhase(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateEvaluationRequestPhase: %v", v)
	}
}

type CreateEvaluationRequest struct {
	Phase CreateEvaluationRequestPhase `json:"phase"`
}

func (c *CreateEvaluationRequest) GetPhase() CreateEvaluationRequestPhase {
	if c == nil {
		return CreateEvaluationRequestPhase("")
	}
	return c.Phase
}
