// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
)

// CreateEvaluationRequestPhase - Checkpoint grades without closing the run; final closes and grades it.
type CreateEvaluationRequestPhase string

const (
	CreateEvaluationRequestPhaseCheckpoint CreateEvaluationRequestPhase = "checkpoint"
	CreateEvaluationRequestPhaseFinal      CreateEvaluationRequestPhase = "final"
)

func (e CreateEvaluationRequestPhase) ToPointer() *CreateEvaluationRequestPhase {
	return &e
}
func (e *CreateEvaluationRequestPhase) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "checkpoint":
		fallthrough
	case "final":
		*e = CreateEvaluationRequestPhase(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateEvaluationRequestPhase: %v", v)
	}
}

type CreateEvaluationRequest struct {
	// Test run whose attributed traffic should be graded.
	TestRunID string `json:"test_run_id"`
	// Checkpoint grades without closing the run; final closes and grades it.
	Phase CreateEvaluationRequestPhase `json:"phase"`
	// Different ready evaluator used to regrade the latest ready capture for this run and phase.
	EvaluatorID optionalnullable.OptionalNullable[string] `json:"evaluator_id,omitzero"`
}

func (c *CreateEvaluationRequest) GetTestRunID() string {
	if c == nil {
		return ""
	}
	return c.TestRunID
}

func (c *CreateEvaluationRequest) GetPhase() CreateEvaluationRequestPhase {
	if c == nil {
		return CreateEvaluationRequestPhase("")
	}
	return c.Phase
}

func (c *CreateEvaluationRequest) GetEvaluatorID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.EvaluatorID
}
