// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type CreateEnvironmentTwinRequest struct {
	// Slug of the twin to serve
	Twin string `json:"twin"`
	// A generated starting state to load into this twin, by `seeds.id`. Omitted starts the twin with its own state and nothing else.
	Seed optionalnullable.OptionalNullable[string] `json:"seed,omitzero"`
	// Generate the first dataset in this twin before it becomes ready.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
}

func (c CreateEnvironmentTwinRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEnvironmentTwinRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEnvironmentTwinRequest) GetTwin() string {
	if c == nil {
		return ""
	}
	return c.Twin
}

func (c *CreateEnvironmentTwinRequest) GetSeed() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Seed
}

func (c *CreateEnvironmentTwinRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Description
}
