// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fa3cd898bf4d

package components

type CreateTestRunRequest struct {
	EnvironmentID string `json:"environment_id"`
	EvaluatorID   string `json:"evaluator_id"`
}

func (c *CreateTestRunRequest) GetEnvironmentID() string {
	if c == nil {
		return ""
	}
	return c.EnvironmentID
}

func (c *CreateTestRunRequest) GetEvaluatorID() string {
	if c == nil {
		return ""
	}
	return c.EvaluatorID
}
