// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateTestRunRequest struct {
	EnvironmentID      string `json:"environment_id"`
	TestVersionID      string `json:"test_version_id"`
	EvaluatorVersionID string `json:"evaluator_version_id"`
}

func (c *CreateTestRunRequest) GetEnvironmentID() string {
	if c == nil {
		return ""
	}
	return c.EnvironmentID
}

func (c *CreateTestRunRequest) GetTestVersionID() string {
	if c == nil {
		return ""
	}
	return c.TestVersionID
}

func (c *CreateTestRunRequest) GetEvaluatorVersionID() string {
	if c == nil {
		return ""
	}
	return c.EvaluatorVersionID
}
