// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type EnvironmentTemplateResponse struct {
	ID        string                            `json:"id"`
	Name      string                            `json:"name"`
	Twins     []EnvironmentTemplateTwinResponse `json:"twins"`
	CreatedAt time.Time                         `json:"created_at"`
}

func (e EnvironmentTemplateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvironmentTemplateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvironmentTemplateResponse) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvironmentTemplateResponse) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EnvironmentTemplateResponse) GetTwins() []EnvironmentTemplateTwinResponse {
	if e == nil {
		return []EnvironmentTemplateTwinResponse{}
	}
	return e.Twins
}

func (e *EnvironmentTemplateResponse) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}
