// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
)

// EnvironmentTemplateTwinResponse - A slot a template asks for, named as a create request names it.
type EnvironmentTemplateTwinResponse struct {
	Twin             string                                    `json:"twin"`
	ScenarioTemplate optionalnullable.OptionalNullable[string] `json:"scenario_template,omitzero"`
	Prompt           optionalnullable.OptionalNullable[string] `json:"prompt,omitzero"`
}

func (e *EnvironmentTemplateTwinResponse) GetTwin() string {
	if e == nil {
		return ""
	}
	return e.Twin
}

func (e *EnvironmentTemplateTwinResponse) GetScenarioTemplate() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ScenarioTemplate
}

func (e *EnvironmentTemplateTwinResponse) GetPrompt() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Prompt
}
