// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type EnvironmentResponse struct {
	ID        string                                       `json:"id"`
	Slug      string                                       `json:"slug"`
	Name      string                                       `json:"name"`
	Status    string                                       `json:"status"`
	Twins     []EnvironmentTwinResponse                    `json:"twins"`
	CreatedAt time.Time                                    `json:"created_at"`
	ExpiresAt optionalnullable.OptionalNullable[time.Time] `json:"expires_at,omitzero"`
}

func (e EnvironmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvironmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvironmentResponse) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvironmentResponse) GetSlug() string {
	if e == nil {
		return ""
	}
	return e.Slug
}

func (e *EnvironmentResponse) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EnvironmentResponse) GetStatus() string {
	if e == nil {
		return ""
	}
	return e.Status
}

func (e *EnvironmentResponse) GetTwins() []EnvironmentTwinResponse {
	if e == nil {
		return []EnvironmentTwinResponse{}
	}
	return e.Twins
}

func (e *EnvironmentResponse) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *EnvironmentResponse) GetExpiresAt() optionalnullable.OptionalNullable[time.Time] {
	if e == nil {
		return nil
	}
	return e.ExpiresAt
}
