// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type EnvironmentTwinResponse struct {
	ID            string `json:"id"`
	EnvironmentID string `json:"environment_id"`
	TwinSlug      string `json:"twin_slug"`
	// The release the current container was started from.
	TwinVersion optionalnullable.OptionalNullable[string] `json:"twin_version,omitzero"`
	// The starting state this twin was created with, if any.
	Seed optionalnullable.OptionalNullable[string] `json:"seed,omitzero"`
	// running or stopped
	DesiredState string `json:"desired_state"`
	// What the twin is actually doing: pending, provisioning, starting, ready, stopping, stopped or failed.
	State string `json:"state"`
	URL   string `json:"url"`
	// Why the current run is not serving, if it is not.
	Failure   optionalnullable.OptionalNullable[string]    `json:"failure,omitzero"`
	CreatedAt time.Time                                    `json:"created_at"`
	ReadyAt   optionalnullable.OptionalNullable[time.Time] `json:"ready_at,omitzero"`
}

func (e EnvironmentTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvironmentTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvironmentTwinResponse) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvironmentTwinResponse) GetEnvironmentID() string {
	if e == nil {
		return ""
	}
	return e.EnvironmentID
}

func (e *EnvironmentTwinResponse) GetTwinSlug() string {
	if e == nil {
		return ""
	}
	return e.TwinSlug
}

func (e *EnvironmentTwinResponse) GetTwinVersion() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.TwinVersion
}

func (e *EnvironmentTwinResponse) GetSeed() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Seed
}

func (e *EnvironmentTwinResponse) GetDesiredState() string {
	if e == nil {
		return ""
	}
	return e.DesiredState
}

func (e *EnvironmentTwinResponse) GetState() string {
	if e == nil {
		return ""
	}
	return e.State
}

func (e *EnvironmentTwinResponse) GetURL() string {
	if e == nil {
		return ""
	}
	return e.URL
}

func (e *EnvironmentTwinResponse) GetFailure() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Failure
}

func (e *EnvironmentTwinResponse) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *EnvironmentTwinResponse) GetReadyAt() optionalnullable.OptionalNullable[time.Time] {
	if e == nil {
		return nil
	}
	return e.ReadyAt
}
