// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type EvaluatorVersionResponseStatus string

const (
	EvaluatorVersionResponseStatusPending EvaluatorVersionResponseStatus = "pending"
	EvaluatorVersionResponseStatusRunning EvaluatorVersionResponseStatus = "running"
	EvaluatorVersionResponseStatusReady   EvaluatorVersionResponseStatus = "ready"
	EvaluatorVersionResponseStatusError   EvaluatorVersionResponseStatus = "error"
)

func (e EvaluatorVersionResponseStatus) ToPointer() *EvaluatorVersionResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EvaluatorVersionResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "running", "ready", "error":
			return true
		}
	}
	return false
}

type EvaluatorVersionResponse struct {
	ID            string                                    `json:"id"`
	TestVersionID string                                    `json:"test_version_id"`
	Version       int64                                     `json:"version"`
	Status        EvaluatorVersionResponseStatus            `json:"status"`
	Twins         []string                                  `json:"twins"`
	ErrorMessage  optionalnullable.OptionalNullable[string] `json:"error_message,omitzero"`
	CreatedAt     time.Time                                 `json:"created_at"`
	// The frozen matchers, once the bundle is ready.
	Rules optionalnullable.OptionalNullable[[]Rule] `json:"rules,omitzero"`
}

func (e EvaluatorVersionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluatorVersionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluatorVersionResponse) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EvaluatorVersionResponse) GetTestVersionID() string {
	if e == nil {
		return ""
	}
	return e.TestVersionID
}

func (e *EvaluatorVersionResponse) GetVersion() int64 {
	if e == nil {
		return 0
	}
	return e.Version
}

func (e *EvaluatorVersionResponse) GetStatus() EvaluatorVersionResponseStatus {
	if e == nil {
		return EvaluatorVersionResponseStatus("")
	}
	return e.Status
}

func (e *EvaluatorVersionResponse) GetTwins() []string {
	if e == nil {
		return []string{}
	}
	return e.Twins
}

func (e *EvaluatorVersionResponse) GetErrorMessage() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ErrorMessage
}

func (e *EvaluatorVersionResponse) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *EvaluatorVersionResponse) GetRules() optionalnullable.OptionalNullable[[]Rule] {
	if e == nil {
		return nil
	}
	return e.Rules
}
