// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6d98c12ce7b3

package components

type EvaluatorProvenance struct {
	Compiler   CompilerProvenance    `json:"compiler"`
	APISchemas []APISchemaProvenance `json:"api_schemas"`
	Executor   ExecutorProvenance    `json:"executor"`
}

func (e *EvaluatorProvenance) GetCompiler() CompilerProvenance {
	if e == nil {
		return CompilerProvenance{}
	}
	return e.Compiler
}

func (e *EvaluatorProvenance) GetAPISchemas() []APISchemaProvenance {
	if e == nil {
		return []APISchemaProvenance{}
	}
	return e.APISchemas
}

func (e *EvaluatorProvenance) GetExecutor() ExecutorProvenance {
	if e == nil {
		return ExecutorProvenance{}
	}
	return e.Executor
}
