// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ExecutorProvenance struct {
	Version string `json:"version"`
}

func (e *ExecutorProvenance) GetVersion() string {
	if e == nil {
		return ""
	}
	return e.Version
}
