// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

// ExportDownloadResponse - A short-lived link to the exported file, which has no other door.
type ExportDownloadResponse struct {
	URL       string    `json:"url"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (e ExportDownloadResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportDownloadResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExportDownloadResponse) GetURL() string {
	if e == nil {
		return ""
	}
	return e.URL
}

func (e *ExportDownloadResponse) GetExpiresAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.ExpiresAt
}
