// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3e53ec6cbba9

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type InvitationResponse struct {
	// WorkOS invitation id
	ID    string           `json:"id"`
	Email string           `json:"email"`
	Role  OrganizationRole `json:"role"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	state     string    `const:"pending" json:"state"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (i InvitationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvitationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvitationResponse) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InvitationResponse) GetEmail() string {
	if i == nil {
		return ""
	}
	return i.Email
}

func (i *InvitationResponse) GetRole() OrganizationRole {
	if i == nil {
		return OrganizationRole("")
	}
	return i.Role
}

func (i *InvitationResponse) GetState() string {
	return "pending"
}

func (i *InvitationResponse) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *InvitationResponse) GetExpiresAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.ExpiresAt
}
