// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f4f88fdb7bea

package components

type InvoicesResponse struct {
	// Issued invoices, newest first
	Invoices []Invoice `json:"invoices"`
}

func (i *InvoicesResponse) GetInvoices() []Invoice {
	if i == nil {
		return []Invoice{}
	}
	return i.Invoices
}
