// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d015fd1119bc

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type InvoicePreview struct {
	PeriodStart *time.Time `json:"period_start"`
	PeriodEnd   *time.Time `json:"period_end"`
	// What is due, after credits
	TotalCents float64 `json:"total_cents"`
	// Credit drawn down against this period's usage
	CreditsAppliedCents *float64          `default:"0" json:"credits_applied_cents"`
	LineItems           []InvoiceLineItem `json:"line_items"`
}

func (i InvoicePreview) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvoicePreview) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvoicePreview) GetPeriodStart() *time.Time {
	if i == nil {
		return nil
	}
	return i.PeriodStart
}

func (i *InvoicePreview) GetPeriodEnd() *time.Time {
	if i == nil {
		return nil
	}
	return i.PeriodEnd
}

func (i *InvoicePreview) GetTotalCents() float64 {
	if i == nil {
		return 0.0
	}
	return i.TotalCents
}

func (i *InvoicePreview) GetCreditsAppliedCents() *float64 {
	if i == nil {
		return nil
	}
	return i.CreditsAppliedCents
}

func (i *InvoicePreview) GetLineItems() []InvoiceLineItem {
	if i == nil {
		return []InvoiceLineItem{}
	}
	return i.LineItems
}
