// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type Method string

const (
	MethodGet     Method = "GET"
	MethodPost    Method = "POST"
	MethodPut     Method = "PUT"
	MethodPatch   Method = "PATCH"
	MethodDelete  Method = "DELETE"
	MethodHead    Method = "HEAD"
	MethodOptions Method = "OPTIONS"
)

func (e Method) ToPointer() *Method {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Method) IsExact() bool {
	if e != nil {
		switch *e {
		case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
			return true
		}
	}
	return false
}

type Matcher struct {
	// Catalog slug of the twin that served the call.
	Twin   string `json:"twin"`
	Method Method `json:"method"`
	// The provider path without a query string. A `{name}` segment matches any single segment, e.g. `/v1/charges/{id}/refund`.
	Path       string      `json:"path"`
	Predicates []Predicate `json:"predicates,omitzero"`
}

func (m Matcher) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Matcher) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Matcher) GetTwin() string {
	if m == nil {
		return ""
	}
	return m.Twin
}

func (m *Matcher) GetMethod() Method {
	if m == nil {
		return Method("")
	}
	return m.Method
}

func (m *Matcher) GetPath() string {
	if m == nil {
		return ""
	}
	return m.Path
}

func (m *Matcher) GetPredicates() []Predicate {
	if m == nil {
		return nil
	}
	return m.Predicates
}
