// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ecd28bb91df9

package components

type OrganizationRole string

const (
	OrganizationRoleAdmin  OrganizationRole = "admin"
	OrganizationRoleMember OrganizationRole = "member"
)

func (e OrganizationRole) ToPointer() *OrganizationRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrganizationRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "admin", "member":
			return true
		}
	}
	return false
}
