// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d31a322ce57d

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type OrganizationMemberResponse struct {
	// WorkOS organization membership id
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	FirstName *string          `json:"first_name"`
	LastName  *string          `json:"last_name"`
	Role      OrganizationRole `json:"role"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	status    string    `const:"active" json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (o OrganizationMemberResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationMemberResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationMemberResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrganizationMemberResponse) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *OrganizationMemberResponse) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *OrganizationMemberResponse) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *OrganizationMemberResponse) GetRole() OrganizationRole {
	if o == nil {
		return OrganizationRole("")
	}
	return o.Role
}

func (o *OrganizationMemberResponse) GetStatus() string {
	return "active"
}

func (o *OrganizationMemberResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}
