// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 351d151c79b0

package components

type PageTwinResponse struct {
	Items []TwinResponse `json:"items"`
	Total int64          `json:"total"`
	Page  int64          `json:"page"`
	Size  int64          `json:"size"`
	Pages int64          `json:"pages"`
}

func (p *PageTwinResponse) GetItems() []TwinResponse {
	if p == nil {
		return []TwinResponse{}
	}
	return p.Items
}

func (p *PageTwinResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageTwinResponse) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageTwinResponse) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageTwinResponse) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
