// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PageEvaluatorVersionSummary struct {
	Items []EvaluatorVersionSummary `json:"items"`
	Total int64                     `json:"total"`
	Page  int64                     `json:"page"`
	Size  int64                     `json:"size"`
	Pages int64                     `json:"pages"`
}

func (p *PageEvaluatorVersionSummary) GetItems() []EvaluatorVersionSummary {
	if p == nil {
		return []EvaluatorVersionSummary{}
	}
	return p.Items
}

func (p *PageEvaluatorVersionSummary) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageEvaluatorVersionSummary) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageEvaluatorVersionSummary) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageEvaluatorVersionSummary) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
