// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c3c2401030f6

package components

type PageAPIKeyResponse struct {
	Items []APIKeyResponse `json:"items"`
	Total int64            `json:"total"`
	Page  int64            `json:"page"`
	Size  int64            `json:"size"`
	Pages int64            `json:"pages"`
}

func (p *PageAPIKeyResponse) GetItems() []APIKeyResponse {
	if p == nil {
		return []APIKeyResponse{}
	}
	return p.Items
}

func (p *PageAPIKeyResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageAPIKeyResponse) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageAPIKeyResponse) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageAPIKeyResponse) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
