// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 63045a1e4bd2

package components

type PageTestResponse struct {
	Items []TestResponse `json:"items"`
	Total int64          `json:"total"`
	Page  int64          `json:"page"`
	Size  int64          `json:"size"`
	Pages int64          `json:"pages"`
}

func (p *PageTestResponse) GetItems() []TestResponse {
	if p == nil {
		return []TestResponse{}
	}
	return p.Items
}

func (p *PageTestResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageTestResponse) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageTestResponse) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageTestResponse) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
