// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PageEvaluatorResponse struct {
	Items []EvaluatorResponse `json:"items"`
	Total int64               `json:"total"`
	Page  int64               `json:"page"`
	Size  int64               `json:"size"`
	Pages int64               `json:"pages"`
}

func (p *PageEvaluatorResponse) GetItems() []EvaluatorResponse {
	if p == nil {
		return []EvaluatorResponse{}
	}
	return p.Items
}

func (p *PageEvaluatorResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageEvaluatorResponse) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageEvaluatorResponse) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageEvaluatorResponse) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
