// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PageSeedResponse struct {
	Items []SeedResponse `json:"items"`
	Total int64          `json:"total"`
	Page  int64          `json:"page"`
	Size  int64          `json:"size"`
	Pages int64          `json:"pages"`
}

func (p *PageSeedResponse) GetItems() []SeedResponse {
	if p == nil {
		return []SeedResponse{}
	}
	return p.Items
}

func (p *PageSeedResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageSeedResponse) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageSeedResponse) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageSeedResponse) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
