// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: eeb4ae02d1fe

package components

type PageMembershipResponse struct {
	Items []MembershipResponse `json:"items"`
	Total int64                `json:"total"`
	Page  int64                `json:"page"`
	Size  int64                `json:"size"`
	Pages int64                `json:"pages"`
}

func (p *PageMembershipResponse) GetItems() []MembershipResponse {
	if p == nil {
		return []MembershipResponse{}
	}
	return p.Items
}

func (p *PageMembershipResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageMembershipResponse) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageMembershipResponse) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageMembershipResponse) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
