// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PageTestVersionResponse struct {
	Items []TestVersionResponse `json:"items"`
	Total int64                 `json:"total"`
	Page  int64                 `json:"page"`
	Size  int64                 `json:"size"`
	Pages int64                 `json:"pages"`
}

func (p *PageTestVersionResponse) GetItems() []TestVersionResponse {
	if p == nil {
		return []TestVersionResponse{}
	}
	return p.Items
}

func (p *PageTestVersionResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PageTestVersionResponse) GetPage() int64 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *PageTestVersionResponse) GetSize() int64 {
	if p == nil {
		return 0
	}
	return p.Size
}

func (p *PageTestVersionResponse) GetPages() int64 {
	if p == nil {
		return 0
	}
	return p.Pages
}
