// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 82ac188ec43e

package components

type PaymentMethodResponse struct {
	// The default payment method, or null when none is saved
	PaymentMethod *PaymentMethod `json:"payment_method"`
}

func (p *PaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if p == nil {
		return nil
	}
	return p.PaymentMethod
}
