// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type Source string

const (
	SourceQuery       Source = "query"
	SourceRequestBody Source = "request_body"
	SourceResponse    Source = "response"
)

func (e Source) ToPointer() *Source {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Source) IsExact() bool {
	if e != nil {
		switch *e {
		case "query", "request_body", "response":
			return true
		}
	}
	return false
}

type Operator string

const (
	OperatorEq       Operator = "eq"
	OperatorNe       Operator = "ne"
	OperatorGt       Operator = "gt"
	OperatorGte      Operator = "gte"
	OperatorLt       Operator = "lt"
	OperatorLte      Operator = "lte"
	OperatorIn       Operator = "in"
	OperatorContains Operator = "contains"
	OperatorExists   Operator = "exists"
)

func (e Operator) ToPointer() *Operator {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Operator) IsExact() bool {
	if e != nil {
		switch *e {
		case "eq", "ne", "gt", "gte", "lt", "lte", "in", "contains", "exists":
			return true
		}
	}
	return false
}

type Value1Type string

const (
	Value1TypeStr     Value1Type = "str"
	Value1TypeInteger Value1Type = "integer"
	Value1TypeNumber  Value1Type = "number"
	Value1TypeBoolean Value1Type = "boolean"
	Value1TypeUnknown Value1Type = "Unknown"
)

type Value1 struct {
	Str        *string         `queryParam:"inline" union:"member"`
	Integer    *int64          `queryParam:"inline" union:"member"`
	Number     *float64        `queryParam:"inline" union:"member"`
	Boolean    *bool           `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type Value1Type
}

func CreateValue1Str(str string) Value1 {
	typ := Value1TypeStr

	return Value1{
		Str:  &str,
		Type: typ,
	}
}

func CreateValue1Integer(integer int64) Value1 {
	typ := Value1TypeInteger

	return Value1{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateValue1Number(number float64) Value1 {
	typ := Value1TypeNumber

	return Value1{
		Number: &number,
		Type:   typ,
	}
}

func CreateValue1Boolean(boolean bool) Value1 {
	typ := Value1TypeBoolean

	return Value1{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValue1Unknown(raw json.RawMessage) Value1 {
	return Value1{
		UnknownRaw: raw,
		Type:       Value1TypeUnknown,
	}
}

func (u Value1) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Value1) IsUnknown() bool {
	return u.Type == Value1TypeUnknown
}

func (u *Value1) UnmarshalJSON(data []byte) error {
	*u = Value1{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeStr,
			Value: &str,
		})
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeInteger,
			Value: &integer,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeNumber,
			Value: &number,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value1TypeBoolean,
			Value: &boolean,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = Value1TypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = Value1TypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(Value1Type)
	switch best.Type {
	case Value1TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case Value1TypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	case Value1TypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case Value1TypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = Value1TypeUnknown
	return nil
}

func (u Value1) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Value1: all fields are null")
}

type Value2Type string

const (
	Value2TypeStr           Value2Type = "str"
	Value2TypeInteger       Value2Type = "integer"
	Value2TypeNumber        Value2Type = "number"
	Value2TypeBoolean       Value2Type = "boolean"
	Value2TypeArrayOfValue1 Value2Type = "arrayOfValue1"
	Value2TypeUnknown       Value2Type = "Unknown"
)

// Value2 - A list for `in`, a number for `gt`/`gte`/`lt`/`lte`, a boolean for `exists`.
type Value2 struct {
	Str           *string         `queryParam:"inline" union:"member"`
	Integer       *int64          `queryParam:"inline" union:"member"`
	Number        *float64        `queryParam:"inline" union:"member"`
	Boolean       *bool           `queryParam:"inline" union:"member"`
	ArrayOfValue1 []*Value1       `queryParam:"inline" union:"member"`
	UnknownRaw    json.RawMessage `json:"-" union:"unknown"`

	Type Value2Type
}

func CreateValue2Str(str string) Value2 {
	typ := Value2TypeStr

	return Value2{
		Str:  &str,
		Type: typ,
	}
}

func CreateValue2Integer(integer int64) Value2 {
	typ := Value2TypeInteger

	return Value2{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateValue2Number(number float64) Value2 {
	typ := Value2TypeNumber

	return Value2{
		Number: &number,
		Type:   typ,
	}
}

func CreateValue2Boolean(boolean bool) Value2 {
	typ := Value2TypeBoolean

	return Value2{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValue2ArrayOfValue1(arrayOfValue1 []*Value1) Value2 {
	typ := Value2TypeArrayOfValue1

	return Value2{
		ArrayOfValue1: arrayOfValue1,
		Type:          typ,
	}
}

func CreateValue2Unknown(raw json.RawMessage) Value2 {
	return Value2{
		UnknownRaw: raw,
		Type:       Value2TypeUnknown,
	}
}

func (u Value2) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Value2) IsUnknown() bool {
	return u.Type == Value2TypeUnknown
}

func (u *Value2) UnmarshalJSON(data []byte) error {
	*u = Value2{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeStr,
			Value: &str,
		})
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeInteger,
			Value: &integer,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeNumber,
			Value: &number,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeBoolean,
			Value: &boolean,
		})
	}

	var arrayOfValue1 []*Value1 = []*Value1{}
	if err := utils.UnmarshalJSON(data, &arrayOfValue1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  Value2TypeArrayOfValue1,
			Value: arrayOfValue1,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = Value2TypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = Value2TypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(Value2Type)
	switch best.Type {
	case Value2TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case Value2TypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	case Value2TypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case Value2TypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case Value2TypeArrayOfValue1:
		u.ArrayOfValue1 = best.Value.([]*Value1)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = Value2TypeUnknown
	return nil
}

func (u Value2) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.ArrayOfValue1 != nil {
		return utils.MarshalJSON(u.ArrayOfValue1, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Value2: all fields are null")
}

// Predicate - One condition on a captured call. Data, never code or SQL.
type Predicate struct {
	Source Source `json:"source"`
	// A key of the decoded query, form or JSON body; dots descend into nested objects and arrays (`metadata.order_id`, `items.0.price`). On `response`, `status_code` is the HTTP status and any other field addresses the response body.
	Field    string   `json:"field"`
	Operator Operator `json:"operator"`
	// A list for `in`, a number for `gt`/`gte`/`lt`/`lte`, a boolean for `exists`.
	Value *Value2 `json:"value"`
}

func (p *Predicate) GetSource() Source {
	if p == nil {
		return Source("")
	}
	return p.Source
}

func (p *Predicate) GetField() string {
	if p == nil {
		return ""
	}
	return p.Field
}

func (p *Predicate) GetOperator() Operator {
	if p == nil {
		return Operator("")
	}
	return p.Operator
}

func (p *Predicate) GetValue() *Value2 {
	if p == nil {
		return nil
	}
	return p.Value
}
