// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RegradeRequest struct {
	EvaluatorVersionID string `json:"evaluator_version_id"`
}

func (r *RegradeRequest) GetEvaluatorVersionID() string {
	if r == nil {
		return ""
	}
	return r.EvaluatorVersionID
}
