// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type RequestLogSummaryResponse struct {
	ID                string    `json:"id"`
	EnvironmentID     string    `json:"environment_id"`
	EnvironmentTwinID string    `json:"environment_twin_id"`
	Method            string    `json:"method"`
	Path              string    `json:"path"`
	QueryString       string    `json:"query_string"`
	StatusCode        int64     `json:"status_code"`
	DurationMs        int64     `json:"duration_ms"`
	OccurredAt        time.Time `json:"occurred_at"`
}

func (r RequestLogSummaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestLogSummaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RequestLogSummaryResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RequestLogSummaryResponse) GetEnvironmentID() string {
	if r == nil {
		return ""
	}
	return r.EnvironmentID
}

func (r *RequestLogSummaryResponse) GetEnvironmentTwinID() string {
	if r == nil {
		return ""
	}
	return r.EnvironmentTwinID
}

func (r *RequestLogSummaryResponse) GetMethod() string {
	if r == nil {
		return ""
	}
	return r.Method
}

func (r *RequestLogSummaryResponse) GetPath() string {
	if r == nil {
		return ""
	}
	return r.Path
}

func (r *RequestLogSummaryResponse) GetQueryString() string {
	if r == nil {
		return ""
	}
	return r.QueryString
}

func (r *RequestLogSummaryResponse) GetStatusCode() int64 {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RequestLogSummaryResponse) GetDurationMs() int64 {
	if r == nil {
		return 0
	}
	return r.DurationMs
}

func (r *RequestLogSummaryResponse) GetOccurredAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.OccurredAt
}
