// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c1a78fe12ea5

package components

type Security struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (s *Security) GetAccessToken() *string {
	if s == nil {
		return nil
	}
	return s.AccessToken
}

func (s *Security) GetOrganizationAPIKey() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationAPIKey
}
