// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type TestVersionResponse struct {
	ID              string            `json:"id"`
	TestID          string            `json:"test_id"`
	Version         int64             `json:"version"`
	TaskDescription string            `json:"task_description"`
	Outcomes        []OutcomeResponse `json:"outcomes"`
	CreatedAt       time.Time         `json:"created_at"`
}

func (t TestVersionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestVersionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestVersionResponse) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TestVersionResponse) GetTestID() string {
	if t == nil {
		return ""
	}
	return t.TestID
}

func (t *TestVersionResponse) GetVersion() int64 {
	if t == nil {
		return 0
	}
	return t.Version
}

func (t *TestVersionResponse) GetTaskDescription() string {
	if t == nil {
		return ""
	}
	return t.TaskDescription
}

func (t *TestVersionResponse) GetOutcomes() []OutcomeResponse {
	if t == nil {
		return []OutcomeResponse{}
	}
	return t.Outcomes
}

func (t *TestVersionResponse) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}
