// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type TestResponse struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	LatestVersionID string    `json:"latest_version_id"`
	CreatedAt       time.Time `json:"created_at"`
}

func (t TestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestResponse) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TestResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TestResponse) GetLatestVersionID() string {
	if t == nil {
		return ""
	}
	return t.LatestVersionID
}

func (t *TestResponse) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}
