// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fe5e09085d93

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
	"github.com/panoratech/twinbay-cli/internal/sdk/types"
)

type TestResponse struct {
	ID string `json:"id"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object          *string           `const:"test" json:"object"`
	Name            string            `json:"name"`
	Version         int64             `json:"version"`
	TaskDescription string            `json:"task_description"`
	Outcomes        []OutcomeResponse `json:"outcomes"`
	Created         int64             `json:"created"`
	Updated         int64             `json:"updated"`
}

func (t TestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestResponse) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TestResponse) GetObject() *string {
	return types.Pointer("test")
}

func (t *TestResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TestResponse) GetVersion() int64 {
	if t == nil {
		return 0
	}
	return t.Version
}

func (t *TestResponse) GetTaskDescription() string {
	if t == nil {
		return ""
	}
	return t.TaskDescription
}

func (t *TestResponse) GetOutcomes() []OutcomeResponse {
	if t == nil {
		return []OutcomeResponse{}
	}
	return t.Outcomes
}

func (t *TestResponse) GetCreated() int64 {
	if t == nil {
		return 0
	}
	return t.Created
}

func (t *TestResponse) GetUpdated() int64 {
	if t == nil {
		return 0
	}
	return t.Updated
}
