// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5e7628e1bbe1

package components

type UpdateTestRequest struct {
	TaskDescription string           `json:"task_description"`
	Outcomes        []OutcomeRequest `json:"outcomes"`
}

func (u *UpdateTestRequest) GetTaskDescription() string {
	if u == nil {
		return ""
	}
	return u.TaskDescription
}

func (u *UpdateTestRequest) GetOutcomes() []OutcomeRequest {
	if u == nil {
		return []OutcomeRequest{}
	}
	return u.Outcomes
}
