// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6f7b73ef4f0b

package components

type UpdateEnvironmentRecordRequest struct {
	// The record's fields, as the provider's API returns them.
	Fields map[string]any `json:"fields"`
}

func (u *UpdateEnvironmentRecordRequest) GetFields() map[string]any {
	if u == nil {
		return map[string]any{}
	}
	return u.Fields
}
