// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7aa2ff9489d2

package components

type UserResponse struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (u *UserResponse) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UserResponse) GetEmail() string {
	if u == nil {
		return ""
	}
	return u.Email
}

func (u *UserResponse) GetFirstName() string {
	if u == nil {
		return ""
	}
	return u.FirstName
}

func (u *UserResponse) GetLastName() string {
	if u == nil {
		return ""
	}
	return u.LastName
}
