// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d0d0928998bf

package components

import (
	"encoding/json"
	"errors"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type LocType string

const (
	LocTypeStr     LocType = "str"
	LocTypeInteger LocType = "integer"
	LocTypeUnknown LocType = "Unknown"
)

type Loc struct {
	Str        *string         `queryParam:"inline" union:"member"`
	Integer    *int64          `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type LocType
}

func CreateLocStr(str string) Loc {
	typ := LocTypeStr

	return Loc{
		Str:  &str,
		Type: typ,
	}
}

func CreateLocInteger(integer int64) Loc {
	typ := LocTypeInteger

	return Loc{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateLocUnknown(raw json.RawMessage) Loc {
	return Loc{
		UnknownRaw: raw,
		Type:       LocTypeUnknown,
	}
}

func (u Loc) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Loc) IsUnknown() bool {
	return u.Type == LocTypeUnknown
}

func (u *Loc) UnmarshalJSON(data []byte) error {
	*u = Loc{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  LocTypeStr,
			Value: &str,
		})
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  LocTypeInteger,
			Value: &integer,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = LocTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = LocTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(LocType)
	switch best.Type {
	case LocTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case LocTypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = LocTypeUnknown
	return nil
}

func (u Loc) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Loc: all fields are null")
}

type Context struct {
}

type ValidationError struct {
	Loc   []Loc    `json:"loc"`
	Msg   string   `json:"msg"`
	Type  string   `json:"type"`
	Input any      `json:"input,omitzero"`
	Ctx   *Context `json:"ctx,omitzero"`
}

func (v ValidationError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ValidationError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *ValidationError) GetLoc() []Loc {
	if v == nil {
		return []Loc{}
	}
	return v.Loc
}

func (v *ValidationError) GetMsg() string {
	if v == nil {
		return ""
	}
	return v.Msg
}

func (v *ValidationError) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *ValidationError) GetInput() any {
	if v == nil {
		return nil
	}
	return v.Input
}

func (v *ValidationError) GetCtx() *Context {
	if v == nil {
		return nil
	}
	return v.Ctx
}
