// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environmentrecords

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitEnvironmentRecordsRoot(parent *cobra.Command) error {
	var EnvironmentRecordsCmd = &cobra.Command{
		Use:         "environment-records",
		Short:       "Operations for environment-records",
		Long:        "Operations for environment-records",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"er"},
	}

	if err := initListCmd(EnvironmentRecordsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(EnvironmentRecordsCmd); err != nil {
		return err
	}

	parent.AddCommand(EnvironmentRecordsCmd)
	return nil
}
