// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package environmentrecords

import (
	"fmt"
	"github.com/panoratech/twinbay-cli/internal/client"
	"github.com/panoratech/twinbay-cli/internal/flagutil"
	"github.com/panoratech/twinbay-cli/internal/output"
	"github.com/panoratech/twinbay-cli/internal/sdk"
	"github.com/panoratech/twinbay-cli/internal/sdk/models/operations"
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "environment-id", FieldPath: "EnvironmentID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment-twin-id", FieldPath: "EnvironmentTwinID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "resource", Shorthand: "r", FieldPath: "Resource", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "external-id", FieldPath: "ExternalID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "fields", Shorthand: "f", FieldPath: "Body.Fields", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"fields"`, Description: "The record's fields, as the provider's API returns them. [required]"},
}

// initUpdateCmd initializes the update command.
func initUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Replace an environment twin record",
		Long:    "Replace an environment twin record",
		Example: "  twinbay environment-records update --environment-id 51d82e18-7a39-41b1-a75a-c9e7e0c04b50 --environment-twin-id d4f89685-95c9-4640-b5a6-df7505d30c25 --resource <value> --external-id <id> --fields '{\"key\":\"<value>\"}'",
		Args:    cobra.NoArgs,
		RunE:    runUpdateCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "update_environment_record",
		},
	}
	flagutil.RegisterFlags(cmd, updateCmdMeta)
	if err := flagutil.ValidateMeta[operations.UpdateEnvironmentRecordRequest](updateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, updateCmdMeta, "Body", "body"); err != nil {
		return fmt.Errorf("annotate body fields for update: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runUpdateCmd executes the update command.
func runUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "update_environment_record")
	}
	req, err := flagutil.BuildRequest[operations.UpdateEnvironmentRecordRequest](cmd, updateCmdMeta, "Body", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.EnvironmentRecords.Update(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
