// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e01d5e93fb2c

package testruns

import (
	"github.com/panoratech/twinbay-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTestRunsRoot(parent *cobra.Command) error {
	var TestRunsCmd = &cobra.Command{
		Use:         "test-runs",
		Short:       "Operations for test-runs",
		Long:        "Operations for test-runs",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"tr"},
	}

	if err := initCreateCmd(TestRunsCmd); err != nil {
		return err
	}

	if err := initListCmd(TestRunsCmd); err != nil {
		return err
	}

	if err := initRetrieveCmd(TestRunsCmd); err != nil {
		return err
	}

	parent.AddCommand(TestRunsCmd)
	return nil
}
